--

--
-- Cost
--

/*
UPDATE Buildings
SET NumCityCostMod = ROUND((NumCityCostMod * 1.1) / 10) * 10
WHERE NumCityCostMod > 0;
*/

/*
UPDATE Buildings	(Type, Happiness)
SELECT				row.BuildingType, row.Yield
FROM				Building_YieldChanges row
WHERE				BuildingType = 
					AND YieldType = 'YIELD_HAPPINESS';
*/

--
-- Specialists
--

UPDATE Specialists
SET GreatPeopleRateChange = 2
WHERE GreatPeopleRateChange > 0;

UPDATE Buildings
SET SpecialistType = 'SPECIALIST_ENGINEER', SpecialistCount = 1
WHERE BuildingClass IN (
	'BUILDINGCLASS_BARRACKS',
	'BUILDINGCLASS_MILITARY_ACADEMY',
	'BUILDINGCLASS_FORGE',
	'BUILDINGCLASS_WORKSHOP',
	'BUILDINGCLASS_FACTORY',
	'BUILDINGCLASS_IRONWORKS',
	'BUILDINGCLASS_HEROIC_EPIC'
);

UPDATE Buildings
SET SpecialistType = 'SPECIALIST_MERCHANT', SpecialistCount = 1
WHERE BuildingClass IN (
	'BUILDINGCLASS_MARKET',
	'BUILDINGCLASS_MINT',
	'BUILDINGCLASS_BANK',
	'BUILDINGCLASS_STOCK_EXCHANGE',
	'BUILDINGCLASS_WAREHOUSE',
	'BUILDINGCLASS_CIRCUS_MAXIMUS',
	'BUILDINGCLASS_NATIONAL_TREASURY'
);

UPDATE Buildings
SET SpecialistType = 'SPECIALIST_SCIENTIST', SpecialistCount = 1
WHERE BuildingClass IN (
	'BUILDINGCLASS_LIBRARY',
	'BUILDINGCLASS_UNIVERSITY',
	'BUILDINGCLASS_PUBLIC_SCHOOL',
	'BUILDINGCLASS_LABORATORY',
	'BUILDINGCLASS_NATIONAL_COLLEGE',
	'BUILDINGCLASS_OXFORD_UNIVERSITY'
);

UPDATE Buildings
SET SpecialistType = 'SPECIALIST_ARTIST', SpecialistCount = 1
WHERE BuildingClass IN (
	'BUILDINGCLASS_SHRINE',
	'BUILDINGCLASS_AMPHITHEATER',
	'BUILDINGCLASS_OPERA_HOUSE',
	'BUILDINGCLASS_MUSEUM',
	'BUILDINGCLASS_BROADCAST_TOWER',
	'BUILDINGCLASS_NATIONAL_EPIC',
	'BUILDINGCLASS_HERMITAGE'
);

UPDATE Buildings
SET SpecialistType = NULL, SpecialistCount = 0
WHERE BuildingClass IN (
	'BUILDINGCLASS_WINDMILL'
);