-- Insert SQL Rules Here

UPDATE CitySpecialization_TargetYields
SET Yield = 50
WHERE YieldType = 'YIELD_FOOD';

--
-- Unit Priorities
--

DELETE FROM Unit_Flavors
WHERE UnitType IN (SELECT Type FROM Units WHERE Class IN (
	'UNITCLASS_CARRIER',
	'UNITCLASS_SCOUT'
));

UPDATE Unit_Flavors SET Flavor = 1
WHERE UnitType IN (SELECT Type FROM Units WHERE Class IN (
	'UNITCLASS_WARRIOR'
));

UPDATE Unit_Flavors SET Flavor = 2
WHERE UnitType IN (SELECT Type FROM Units WHERE Class IN (
	'UNITCLASS_TRIREME',
	'UNITCLASS_ARCHER',
	'UNITCLASS_SPEARMAN',
	'UNITCLASS_SENTINEL'
)) OR UnitType IN (
	'UNIT_AZTEC_JAGUAR'
);

UPDATE Unit_Flavors SET Flavor = 3
WHERE UnitType IN (SELECT Type FROM Units WHERE Class IN (
	'UNITCLASS_COMPOSITE_BOWMAN',
	'UNITCLASS_CATAPULT'
)) OR UnitType IN (
	'UNIT_GREEK_HOPLITE',
	'UNIT_PERSIAN_IMMORTAL'
);

UPDATE Unit_Flavors SET Flavor = 4
WHERE UnitType IN (SELECT Type FROM Units WHERE Class IN (
	'UNITCLASS_CHARIOT_ARCHER',
	'UNITCLASS_HORSEMAN',
	'UNITCLASS_SWORDSMAN',

	'UNITCLASS_GALLEASS',
	'UNITCLASS_PIKEMAN',
	'UNITCLASS_LEVY'
));

UPDATE Unit_Flavors SET Flavor = 6
WHERE UnitType IN (SELECT Type FROM Units WHERE Class IN (
	'UNITCLASS_CROSSBOWMAN',
	'UNITCLASS_TREBUCHET',

	'UNITCLASS_CARAVEL'
));

UPDATE Unit_Flavors SET Flavor = 8
WHERE UnitType IN (SELECT Type FROM Units WHERE Class IN (
	'UNITCLASS_KNIGHT',
	'UNITCLASS_LONGSWORDSMAN',

	'UNITCLASS_PRIVATEER',
	'UNITCLASS_FRIGATE',
	'UNITCLASS_MUSKETMAN'
));

UPDATE Unit_Flavors SET Flavor = 12
WHERE UnitType IN (SELECT Type FROM Units WHERE Class IN (
	'UNITCLASS_SKIRMISHER',
	'UNITCLASS_SHIP_OF_THE_LINE',
	'UNITCLASS_CANNON'
)) OR UnitType IN (
	'UNIT_FRENCH_MUSKETEER'
);

UPDATE Unit_Flavors SET Flavor = 16
WHERE UnitType IN (SELECT Type FROM Units WHERE Class IN (
	'UNITCLASS_LANCER',
	'UNITCLASS_CAVALRY',
	'UNITCLASS_RIFLEMAN',
	'UNITCLASS_GATLINGGUN',

	'UNITCLASS_SUBMARINE',
	'UNITCLASS_DESTROYER'
)) OR UnitType IN (
	'UNIT_AMERICAN_MINUTEMAN'
);

UPDATE Unit_Flavors SET Flavor = 24
WHERE UnitType IN (SELECT Type FROM Units WHERE Class IN (
	'UNITCLASS_ARTILLERY',
	'UNITCLASS_IRONCLAD',
	'UNITCLASS_CONSCRIPT',
	'UNITCLASS_GREAT_WAR_INFANTRY',
	'UNITCLASS_TRIPLANE',
	'UNITCLASS_WWI_BOMBER'

));

UPDATE Unit_Flavors SET Flavor = 32
WHERE UnitType IN (SELECT Type FROM Units WHERE Class IN (
	'UNITCLASS_MACHINE_GUN',
	'UNITCLASS_WWI_TANK',
	'UNITCLASS_ANTI_AIRCRAFT_GUN',
	'UNITCLASS_MARINE',
	'UNITCLASS_INFANTRY'
));

UPDATE Unit_Flavors SET Flavor = 64
WHERE UnitType IN (SELECT Type FROM Units WHERE Class IN (
	'UNITCLASS_NUCLEAR_SUBMARINE',
	'UNITCLASS_BATTLESHIP',
	'UNITCLASS_FIGHTER',
	'UNITCLASS_BOMBER',
	'UNITCLASS_TANK',
	'UNITCLASS_ANTI_TANK_GUN',

	'UNITCLASS_PARATROOPER',
	'UNITCLASS_MECHANIZED_INFANTRY',
	'UNITCLASS_MOBILE_SAM',
	'UNITCLASS_GUIDED_MISSILE',
	'UNITCLASS_HELICOPTER_GUNSHIP',
	'UNITCLASS_ATOMIC_BOMB'
));

UPDATE Unit_Flavors SET Flavor = 96
WHERE UnitType IN (SELECT Type FROM Units WHERE Class IN (
	'UNITCLASS_MISSILE_CRUISER',
	'UNITCLASS_ROCKET_ARTILLERY',
	'UNITCLASS_JET_FIGHTER',
	'UNITCLASS_STEALTH_BOMBER',
	'UNITCLASS_MODERN_ARMOR',
	'UNITCLASS_NUCLEAR_MISSILE'
));

UPDATE Unit_Flavors SET Flavor = 128
WHERE UnitType IN (SELECT Type FROM Units WHERE Class IN (
	'UNITCLASS_MECH'
));






UPDATE Unit_Flavors SET Flavor = ROUND(Flavor * 1.5, 0)
WHERE FlavorType = 'FLAVOR_DEFENSE' 
AND UnitType IN (SELECT Type FROM Units WHERE CombatClass IN (
	'UNITCOMBAT_ARCHER',
	'UNITCOMBAT_MOUNTED_ARCHER',
	'UNITCOMBAT_FIGHTER',
	'UNITCOMBAT_BOMBER'
));

UPDATE Unit_Flavors SET Flavor = ROUND(Flavor * 0.67, 0)
WHERE FlavorType = 'FLAVOR_DEFENSE' 
AND UnitType IN (SELECT UnitType FROM Unit_ResourceQuantityRequirements);

--
-- Building Priorities
--

UPDATE Building_Flavors
SET Flavor = Flavor * 0.5
WHERE FlavorType = 'FLAVOR_WONDER' AND BuildingType IN (
	'BUILDING_GREAT_LIGHTHOUSE',
	'BUILDING_COLOSSUS',
	'BUILDING_STONEHENGE',
	'BUILDING_STATUE_ZEUS',
	'BUILDING_ANGKOR_WAT',
	'BUILDING_HIMEJI_CASTLE',
	'BUILDING_MACHU_PICCHU',
	'BUILDING_TEMPLE_ARTEMIS',
	'BUILDING_LOUVRE',
	'BUILDING_MAUSOLEUM_HALICARNASSUS'
);

UPDATE Building_Flavors
SET Flavor = Flavor * 2
WHERE FlavorType = 'FLAVOR_WONDER' AND BuildingType IN (
	'BUILDING_GREAT_LIBRARY',
	'BUILDING_HAGIA_SOPHIA',
	'BUILDING_NOTRE_DAME',
	'BUILDING_HANGING_GARDEN',
	'BUILDING_ORACLE'
);