INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_ARCHER', 'Cazador furtivo', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_SPEARMAN', 'Saqueador', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_SWORDSMAN', 'Desvalijador', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_PIKEMAN', 'Mercenario', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_CROSSBOWMAN', 'Asesino', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_LONGSWORDSMAN', 'Proscrito', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_MUSKETMAN', 'Delincuente', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_RIFLEMAN', 'Agitador', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_INFANTRY', 'Partisano', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_PARATROOPER', 'Guerrillero', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_MECHANIZED_INFANTRY', 'Rebelde', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_CHARIOT_ARCHER', 'Cazador', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_HORSEMAN', 'Merodeador', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_KNIGHT', 'Ladrón', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_LANCER', 'Salteador de caminos', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_CAVALRY', 'Bandido', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_MECH', 'Pícaro', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_GALLEY', 'Esclavista', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_TRIREME', 'Pirata', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_GALLEASS', 'Bucanero', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_FRIGATE', 'Corsario', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_IRONCLAD', 'Asaltante', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_UNIT_BARBARIAN_SUBMARINE', 'Contrabandista', '', '');
