--· ES_ES/Cities.sql
/* General */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GEM_VERSION', 'GEM v1.{1_num}', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_MISSION_START_GOLDENAGE_HELP', 'Esta orden consumirá al Gran Personaje y comenzará una Edad de Oro [ICON_GOLDEN_AGE] (+20% de producción en todas las ciudades) durante {1_Num} turnos. Cada vez que un Gran Personaje comienza una Edad de Oro, la duración se reducirá (hasta un mínimo de 3 turnos).', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRADE_ROUTE_INCOME_INFO', '+{1_Num} Oro [ICON_GOLD] por ruta comercial[NEWLINE]+{2_Num} Oro[ICON_GOLD] por [ICON_CITIZEN] Ciudadano en la capital[NEWLINE]+{3_Num} Oro [ICON_GOLD] por Ciudadano [ICON_CITIZEN]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_MISSION_HURRY_PRODUCTION_HELP', 'Otorga (200 + 30 * [ICON_CITIZEN] Población) [ICON_PRODUCTION] Producción para la construcción actual de la ciudad. Esto consume al Gran Personaje.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_PRODUCTION_BUILDING_ALLOWS_WATER_ROUTES_EXTRA', 'Una ruta comercial [ICON_CONNECTED] de carreteras, ferrocaril o marítima a la Capital produce Oro [ICON_GOLD].[NEWLINE][NEWLINE]Una ruta de ferrocarril [ICON_CONNECTED_RAILROAD] o marítima a la Capital proporciona +25% Producción [ICON_PRODUCTION] (con la tecnología [COLOR_POSITIVE_TEXT]Ferrocarril[ENDCOLOR]).[NEWLINE][NEWLINE]Los [COLOR_POSITIVE_TEXT]Faros[ENDCOLOR] proporcionan una conexión segura entre rutas comerciales marítimas y terrestres.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_IMPROVEMENT_TRADING_POST', 'Villa', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_CIV5_IMPROVEMENTS_TRADING_POST_TEXT', 'Una villa es un grupo de asentamientos o comunidad con una población que oscila entre cientos y varios miles habitantes. Estos pequeños asentamientos se unen a tu sociedad económica.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_CIV5_IMPROVEMENTS_TRADINGPOST', 'Villa', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_GOLD_TRADINGPOST_ADV_QUEST', '¿Proporciona oro la villa?', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_GOLD_TRADINGPOST_HEADING3_BODY', 'Construir una mejora de villa en una casilla para mejorar su rendimiento de oro.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_GOLD_TRADINGPOST_HEADING3_TITLE', 'La Villa', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_WORKERS_TRADINGPOST_HEADING3_BODY', 'La Villa incrementa la producción de oro en 1 en una casilla. No necesita acceso a un recurso.[NEWLINE]Tecnología Necesaria: Caza[NEWLINE]Tiempo de Construcción: 5 turnos[NEWLINE]Puede ser Construida en: Cualquier tipo de tierra, excepto hielo', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_BUILD_TRADING_POST', 'Construir una [LINK=IMPROVEMENT_TRADING_POST]Villa[\LINK]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_BUILD_GOLD_REC', 'Incrementará la cantidad de Oro [ICON_GOLD] producida por esta casilla, ¡aumentando la cantidad de dinero que tendremos para gastar!', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_TP_GOLDEN_AGE_EFFECT', 'Las Ciudades ganan +20% de producción durante Edades de Oro [ICON_GOLDEN_AGE].[NEWLINE]+20% Excedente de Comida [ICON_FOOD][NEWLINE]+20% Producción [ICON_PRODUCTION][NEWLINE]+20% Oro [ICON_GOLD][NEWLINE]+20% Science [ICON_RESEARCH][NEWLINE]+20% Cultura [ICON_CULTURE][NEWLINE]+20% Fe [ICON_PEACE][NEWLINE][NEWLINE]El excedente de felicidad sigue añadiendose al contador de Edad de Oro mientras estás en una Edad de Oro.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_BUILDING_MACHU_PICHU_HELP', 'Una montaña cerca de la ciudad gana:[NEWLINE]Comida: 5 [ICON_FOOD][NEWLINE]Oro: 5 [ICON_GOLD][NEWLINE]Culture: 5 [ICON_CULTURE][NEWLINE]Fe: 5 [ICON_PEACE]', '', '');
/* Food */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_FLOATING_GARDENS_DESC', 'Chinampa', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_FOATING_GARDENS_STRATEGY', 'El Chinampa es el edificio único Azteca, remplaza al Molino de Agua. Incrementa el flujo de alimentos a la ciudad, y solo puede ser construido si la ciudad está cerca de un lago o un río.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_FLOATING_GARDENS_PEDIA', 'Un Chinampa  es una pequeña isla artificial construida en un lago de agua dulce para aumentar la cantidad de tierras disponibles para la agricultura. El lago irriga la isla y la provee con material organico. El resultado es un entorno increiblemente fértil. Los Aztecas eran maestros en este tipo de agriculura, y los ''Jardines Flotantes de Xochimilco'' siguen siendo famosos hoy en día.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_SANITATION_SYSTEM', 'Sistema de Saneamiento', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_SANITATION_SYSTEM_PEDIA', 'El saneamiento es el medio por el que a través de la higiene se mejora la salud y la prevención del contacto humano con los residuos tóxicos.[NEWLINE][NEWLINE]Los residuos pueden ser agentes infecciosos físicos, microbiológicos, biologicos o químicos. LA higiene que se encarga de la prevención puede proporcionarse a través de soluciones de ingeniería (como el alcantarillado o el tratamiento de aguas residuales), tecnologías simples (letrinas, tanques sépticos), o incluso con prácticas personales de higiene (lavándose las manos con jabón).', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_VACCINATIONS', 'Vacunas', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_VACCINATIONS_PEDIA', 'Una vacuna es el preparado biológico que mejora la inmunidad a un tipo particular de enfermedad. La vacuna estimula el sistema inmunitario del cuerpo para reconocer un agente de enfermedad, destruirlo y "recordarlo", por lo que el sistema inmune puede reconocer y destruir más facilmente cualquiera de esos microorganismos en posteriores encuentros. La Vacunación es el método más efectivo en prevención de enfermerdades infecciosas.[NEWLINE][NEWLINE]El esfuerzo global de la humanidad en la vacunación erradicó la viruela, y restringió otras enfermedades mortales como la polio, sarampión, y tétano. La Viruela mató aproximadamente un 90% delos Nativos Americanos después del contacto con Eurasia en los 1500s. Cuando finalmente fue erradicada en 1979, la viruale había matado aproximadamente 300–500 millones de personas en el mundo tan solo en el pasado siglo, más que todas las guerras del siglo 20 juntas. La Viruela fue la primera enfermedad para la que se produjo una vacuna en 1796. La inmunización fue llamada vacuna porque ésta derivaba de un virus que afectaba a las vacas (Latin: vacca - vaca).', '', '');
/* Production */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_WORKSHOP_STRATEGY', 'El Taller incrementa la producción cuando construyes edificios. Las Ciudades en colinas no pueden construir talleres.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_STABLE_STRATEGY', 'El Establo incrementa la velocidad de producción de las unidades montadas y añade producción por ciertos recursos.', '', '');
/* Gold */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_MINT_STRATEGY', 'La Ceca incrementa los ingresos de Oro [ICON_GOLD] de la Ciudad y los ingresos de oro por ciertos productos.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_WAREHOUSE', 'Almacén', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_WAREHOUSE_PEDIA', 'Un Almacén es un edificio comercial para el almacenamiento de mercancías. Los Almacenes son usados por los fabricantes, importadores, exportadores, distribuidores, transportistas, clientes, etc. Las mercancías almacenadas abarcan cualquier tipo de materia prima, materiales empaquetados, repuestos, componentses, o bienes manufacturados asociados con la agricultura, fabricación, o comercio.', '', '');
/* Science */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_MENTORS_HALL', 'Mentors Hall', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_MENTORS_HALL_PEDIA', 'Mentoring is an organized process for the transmission of knowledge, social capital, and the psychosocial support perceived by the recipient as relevant to work, career, or professional development. Mentoring entails informal communication, usually face-to-face and during a sustained period of time, between a person who is perceived to have greater relevant knowledge, wisdom, or experience (the mentor) and a person who is perceived to have less (the protégé).', '', '');
/* Culture */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_BUILDING_RADIO_STATION', 'Radio Station', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_BUILDING_RADIO_STATION_PEDIA', 'Radio broadcasting is a one-way wireless transmission over radio waves intended to reach a wide audience.[NEWLINE][NEWLINE]The earliest radio stations were simply radiotelegraphy systems, and did not carry audio. In the early 1920s, the first audio stations were established by radio equipment manufacturers and retailers who offered radio programs in order to sell more radios to consumers.[NEWLINE][NEWLINE]When the practice of sponsoring programs was popularised, each individual radio program was usually sponsored by a single business in exchange for a brief mention of the business'' name at the beginning and end of the sponsored shows. However, radio station owners soon realised they could earn more money by selling sponsorship rights in small time allocations to multiple businesses throughout their radio station''s broadcasts, rather than selling the sponsorship rights to single businesses per show.', '', '');
/* Happiness */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_STONE_WORKS_STRATEGY', 'Stone Works can only be constructed in a city near an improved [ICON_RES_STONE] Stone or [ICON_RES_MARBLE] Marble resource. Stone Works increase a city''s [ICON_PRODUCTION] production.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_BUILDING_ARENA', 'Arena', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_BUILDING_ARENA_PEDIA', 'An arena is an enclosed area, often circular or oval-shaped, frequently designed to showcase sporting events. The word derives from Latin harena, a particularly fine/smooth sand used to absorb blood in ancient arenas like the Colosseum in Rome.[NEWLINE][NEWLINE]Arenas are composed of a large open space surrounded on most or all sides by tiered seating for spectators. The key feature of an arena is that the event space is the lowest point, allowing for maximum visibility. An arena is usually designed to accommodate a fairly large number of spectators.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_BUILDING_PUBLISHING_HOUSE', 'Publishing House', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_BUILDING_PUBLISHING_HOUSE_PEDIA', 'Publishing is the activity of making information available to general public. In some cases, authors may be their own publishers, meaning: originators and developers of content also provide media to deliver and display the content for the same.[NEWLINE][NEWLINE]Traditionally, the term refers to the distribution of printed works such as books (the "book trade") and newspapers. With the advent of digital information systems and the Internet, the scope of publishing has expanded to include electronic resources, such as the electronic versions of books and periodicals, as well as micropublishing, websites, blogs, video game publishers and the like.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_BUILDING_CINEMA', 'Cinema', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_BUILDING_CINEMA_PEDIA', 'A cinema (or movie theater in North America) is a venue for viewing film.[NEWLINE][NEWLINE]Most but not all movie theaters are commercial operations catering to the general public, who attend by purchasing a ticket. The movie is projected with a movie projector onto a large projection screen at the front of the auditorium. Most movie theaters are now equipped for digital cinema projection, removing the need to create and transport a physical film print.', '', '');
/* Other */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_SUPERMAX_PRISON', 'Supermax Prison', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_SUPERMAX_PRISON_PEDIA', 'Supermax (short for "super-maximum security") is the name used to describe "control-unit" prisons, or units within prisons, which represent the most secure levels of custody in the prison systems of certain countries. The objective is to provide long term, segregated housing for inmates classified as the highest security risks in the prison system - the "worst of the worst" criminals, and those who pose a threat to national and international security.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-25'), 'TXT_KEY_BUILDING_CAPITAL_BUILDING', 'Capital', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_CAPITAL_BUILDING_PEDIA', 'The seat of government is the building, complex of buildings or city from which a government exercises its authority. The seat of government is usually located in the capital. In some countries the seat of government differs from the capital, e.g. in the Netherlands where The Hague is the seat of government and Amsterdam is the de jure capital of the Netherlands. In most it is the same city, for example Moscow as the capital and seat of government of Russia. In the United Kingdom, the seat of government is London, the capital, or more specifically the City of Westminster.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-25'), 'TXT_KEY_BUILDING_GREAT_HALL', 'Great Hall', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_GREAT_HALL_PEDIA', 'A city hall is the chief administrative building of a city, town, or other municipality. It usually houses the city or town council, its associated departments, and their employees. It also usually functions as the base of the mayor of a city, town, borough, or county.[NEWLINE][NEWLINE]The local government may endeavour to use the townhall building to promote and enhance the quality of life of the community. In many cases, "''town halls'' serve not only as buildings for government functions, but also have facilities for various civic and cultural activities. These may include art shows, stage performances, exhibits and festivals. As symbols of local government, city and town halls have distinctive architecture, and the buildings may have great historical significance.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_PALACE', 'Palace', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_PALACE_PEDIA', 'A palace is a grand residence, especially a royal residence or the home of a head of state or some other high-ranking dignitary, such as a bishop or archbishop.[NEWLINE][NEWLINE]The word derives from the Latin name Palatium, for Palatine Hill, one of the seven hills in Rome. In many parts of Europe, the term is also applied to ambitious private mansions of the aristocracy. Many historic palaces are now put to other uses such as parliaments, museums, hotels or office buildings. The word is also sometimes used to describe a lavishly ornate building used for public entertainment or exhibitions.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_POPUP_CITY_CAPTURE_INFO', 'What would you like to do with this City?', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_POPUP_ANNEX_PUPPET', '[ICON_OCCUPIED] [COLOR_POSITIVE_TEXT]Occupy[ENDCOLOR]: Better for large cities. Building a Courthouse converts this into a normal city.[NEWLINE][NEWLINE][ICON_PUPPET] [COLOR_POSITIVE_TEXT]Puppet[ENDCOLOR]: Better for small cities. Puppets have 3 basic [ICON_HAPPINESS_4] Unhappiness per-city (instead of 4) and do not increase Policy costs.[NEWLINE][NEWLINE]Occupied cities and Puppets produce lower yields than normal cities.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_POPUP_ANNEX_CITY', 'Occupy the City', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_POPUP_CITY_CAPTURE_INFO_PUPPET', 'You may later [ICON_OCCUPIED] Occupy a puppeted city at any time.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_CIV5_BABYLON_WALLS_STRATEGY', 'The Walls of Babylon are a Babylonian Unique Building, replacing the standard city Walls. The Walls of Babylon increases a city''s Defense Strength and Hit Points (both significantly more than standard Walls.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_WALLS_STRATEGY', 'Walls increase a city''s Defense Strength and Hit Points, making the city more difficult to capture. Walls are quite useful for cities located along a civilizations frontier.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_MILITARY_BASE_STRATEGY', 'The Military Base is a mid-game building which increases the city''s Defensive Strength and Hit Points. The city must possess an Arsenal before a Military Base may be constructed.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_CASTLE_STRATEGY', 'The Castle is a Medieval-era building which increases the city''s Defensive Strength and Hit Points. The city must possess Walls before the Castle can be constructed.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_ARSENAL_STRATEGY', 'The Arsenal is a mid-game military building that increases a city''s Defense Strength and Hit Points, making the city more difficult to capture. The city must possess a Castle before it can construct an Arsenal.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_MUGHAL_FORT_STRATEGY', 'The Mughal Fort is a Medieval-era building that increases the city''s Defense Strength, Hit Points, and provides some [ICON_CULTURE] Culture every turn. It is the Indian unique building, replacing the Castle. After Flight is learned, it provides a [ICON_GOLD] Gold bonus to the city as well. Building Walls is a prerequisite for building the Mughal Fort.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_GARDEN_STRATEGY', 'The Garden increases the speed at which [ICON_GREAT_PEOPLE] Great People are generated in the city.', '', '');
/* National Wonders */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_HEROIC_EPIC_HELP', 'All newly-trained Units in this City receive the [COLOR_POSITIVE_TEXT]Morale[ENDCOLOR] Promotion, improving [ICON_STRENGTH] combat strength by 15%.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_OXFORD_UNIVERSITY', 'Heidelberg University', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_HOLY_PALACE', 'Holy Palace', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_HOLY_PALACE_HELP', 'Provides +8 and 25% Faith in the city it is constructed in.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_HOLY_PALACE_STRATEGY', 'The Holy Palace provides significant faith to a city.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_HOLY_PALACE_PEDIA', 'Todo', '', '');
/* Wonders */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_PANAMA_CANAL', 'Panama Canal', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_PANAMA_CANAL_HELP', '[ICON_MOVES] +1 Movement for Ships', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_PARTHENON', 'Parthenon', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_PARTHENON_HELP', '[ICON_STRENGTH] +10% Strength from Great Generals and Admirals', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_GREATWALL_DESC', 'The Great Wall of China is one of the largest and most famous man-made constructions in the entire world. Chinese rulers built the Great Wall to ward off attack from nomadic tribesmen living in modern Manchuria and Mongolia. Interestingly, the Great Wall was not designed to keep the nomads out - the Chinese knew it was all but impossible to defend such a long border - it was designed to make it difficult for the raiders to carry off loot, thus making raids far less profitable and thus less worth the risks involved.[NEWLINE][NEWLINE]There have actually been five different "Great Walls" built by different Chinese dynasties. Several walls were being built as early as the 7th century BCE. These, later joined together and made bigger, stronger, and unified are now collectively referred to as the Great Wall. The majority of the existing wall was reconstructed during the Ming Dynasty between 1368 and 1640 AD. This wall was constructed on a grander scale, using more permanent materials (like stone). The Ming wall stretches for 3,948 miles from Shanhai Pass on the Bohai Gulf in the east to Lop Nur in the southeast portion of Xinjiang''s Uygur Autonomous Region in the west. This was the region where the Silk Road first entered China, and a series of watchtowers which could communicate via smoke signals were intended to pass messages rapidly along the wall''s vast length.[NEWLINE][NEWLINE]In pure military terms, the Great Wall turned out to be something of a failure. The Manchus were able to bribe a Chinese general to let them pass through the wall, so it turned out to be of little value in stopping a major barbarian attack. After the Manchus conquered China, the borders of the country extended far to the north, rendering the wall irrelevant. The sheer monetary cost of the wall was also staggering, and the cost in human lives is said to have exceeded over one million souls. The Great Wall is sometimes nicknamed "the long graveyard."[NEWLINE][NEWLINE]Today much of the Great Wall is in a state of disrepair - though the tourist regions are well-preserved, much of the rest of the structure is crumbling, and perhaps only 20% of the wall is in good condition. Despite its decay, the Great Wall remains one of China''s most popular tourist attractions and a true wonder of the world.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_PENTAGON_HELP', 'All units heal every turn.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_STATUE_ZEUS', 'Parthenon', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_STATUE_ZEUS_HELP', 'Increases the power of Great Generals. [NEWLINE] Provides a [ICON_TEAM_7] Great General.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_STATUE_ZEUS_QUOTE', '[NEWLINE][TAB][TAB]"As you enter the temple that they name the Parthenon, all the sculptures you see on what is called the pediment refer to the birth of Athena, those on the rear pediment represent the contest for the land between Athena and Poseidon."[NEWLINE][TAB][TAB] - Pausanias (Description of Greece, I, 24, 5)[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_STATUE_ZEUS_DESC', 'The Parthenon is a temple in the Athenian Acropolis dedicated to the Greek goddess Athena, whom the people of Athens considered their protector. It was build during the time Athens was the superior military and trading power in the Mediterranean. It is the most important surviving building of Classical Greece, generally considered to be the culmination of the development of the Doric order. Its decorative sculptures are considered some of the high points of Greek art. The Parthenon is regarded as an enduring symbol of Ancient Greece and of Athenian democracy and one of the world''s greatest cultural monuments.[NEWLINE][NEWLINE]Its construction began in 447 BC and was completed in 438 BC, although decorations of the Parthenon continued until 432 BC. The Parthenon itself replaced an older temple of Athena, which historians call the Pre-Parthenon or Older Parthenon, that was destroyed in the Persian invasion of 480 BC. Like most Greek temples, the Parthenon was used as a treasury. For a time, it served as the treasury of the Delian League, which later became the Athenian Empire.[NEWLINE][NEWLINE]The first endeavor to build a sanctuary for Athena Parthenos on the site of the present Parthenon was begun shortly after the Battle of Marathon (c. 490-488 BC) upon a muscular limestone foundation that extended and leveled the southern part of the Acropolis summit. In the mid-5th century BC, when Athens was the greatest cultural center of its time, Pericles initiated an ambitious building project that lasted the entire second half of the century. The most important buildings visible on the Acropolis today, the Parthenon, the Propylaia, the Erechtheion and the temple of Athena Nike, were erected during this period. The Parthenon was built under the general supervision of the sculptor Phidias, who also had charge of the sculptural decoration, and the architects were Iktinos and Kallikrates.[NEWLINE][NEWLINE]In the 5th century AD, the Parthenon was converted into a Christian church dedicated to the Virgin Mary. After the Ottoman Turk conquest, it was turned into a mosque in the early 1460s, and it had a minaret built in it. On 26 September 1687, an Ottoman Turk ammunition dump inside the building was ignited by Venetian bombardment. The resulting explosion severely damaged the Parthenon and its sculptures. In 1806, Thomas Bruce, a British nobleman and diplomat, removed some of the surviving sculptures, with the Ottoman Turks'' permission. These sculptures, now known as the Elgin Marbles or the Parthenon Marbles, were sold in 1816 to the British Museum in London, where they are now displayed.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_LEANING_TOWER', 'Duomo', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_LEANING_TOWER_QUOTE', '[NEWLINE][TAB][TAB]"The Renaissance of the fifteenth century was, in many things, great rather by what it designed then by what it achieved. "[NEWLINE][TAB][TAB] - Walter Pater[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_LEANING_TOWER_DESC', 'The Duomo (Basilica di santa maria del fiore) is a large cathedral located in the heart of Florence, Italy. It took 140 years to construct, finishing in 1436. During construction, Florence was a republic, part of many City-states in Italy during the time. The Cathedral played a core part in the republic and is said to have started the Renaissance.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_HUBBLE', 'Bell Labs', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_HUBBLE_QUOTE', '[NEWLINE][TAB][TAB]"An institute of creative technology requires a critical mass of talented people to foster a busy exchange of ideas."[NEWLINE][TAB][TAB] - Mervin Kelly, president of Bell Labs[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_HUBBLE_DESC', 'This research institution revolutionized the world by inventing the fundamental components of modern computers, including the most important engineering marvel of the 20th century: transistors. These devices allowed computers to shrink from house-size to pocket-size while drastically increasing their power.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_MAUSOLEUM_HALICARNASSUS', 'Flavian Amphitheatre', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_MAUSOLEUM_HALICARNASSUS_DESC', 'Commonly known as *The* Colosseum, this elliptical amphitheater in the centre of the city of Rome is the largest ever built in the Roman Empire. It is considered one of the greatest works of Roman architecture and Roman engineering.[NEWLINE][NEWLINE]Occupying a site just east of the Roman Forum, its construction started in 72 AD under the emperor Vespasian and was completed in 80 AD under Titus, with further modifications being made during Domitian''s reign (81–96 AD). The name Amphitheatrum Flavium derives from both Vespasian''s and Titus''s family name (Flavius, from the gens Flavia).[NEWLINE][NEWLINE]Capable of seating 50,000 spectators, the Colosseum was used for gladiatorial contests and public spectacles such as mock sea battles, animal hunts, executions, re-enactments of famous battles, and dramas based on Classical mythology. The building ceased to be used for entertainment in the early medieval era. It was later reused for such purposes as housing, workshops, quarters for a religious order, a fortress, a quarry, and a Christian shrine.[NEWLINE][NEWLINE]The name Colosseum has long been believed to be derived from a colossal statue of Nero nearby. This statue was later remodeled by Nero''s successors into the likeness of Helios or Apollo, the sun god, by adding the appropriate solar crown. Nero''s head was also replaced several times with the heads of succeeding emperors. The Colossus did eventually fall, possibly being pulled down to reuse its bronze. By the year 1000 the name Colosseum had been coined to refer to the amphitheatre. The statue itself was largely forgotten and only its base survives, situated between the Colosseum and the nearby Temple of Venus and Roma.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_MAUSOLEUM_HALICARNASSUS_QUOTE', '[NEWLINE][TAB][TAB]"What am I to say about that dreadful place, the amphitheatre? Even perjury could not face it. For it is dedicated to more names, and more awful names, than the Capitol itself; it is the temple of all demons. There are as many unclean spirits gathered there as it can seat men."[NEWLINE][TAB][TAB] - Tertullian (De Spectaculis, XII)[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_HAGIA_SOPHIA_HELP', 'Adds cathderal bonuses to the city it is constructed in.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_ITAIPU_DAM', 'Itaipu Dam', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_ITAIPU_DAM_HELP', 'Provides production in every city. [NEWLINE] Provides a free engineer specialist. [NEWLINE]Provides a free Hydro Plant in the city. [NEWLINE]Must be built on a river.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_ITAIPU_DAM_QUOTE', '[NEWLINE][TAB][TAB]"Women think that an engineer is a man in hip boots building a dam. They don''t realize that 95 percent of engineering is done in a nice air-conditioned office."[NEWLINE][TAB][TAB] - Beatrice Alice Hicks, first female engineer at Western Electric.[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_ITAIPU_DAM_DESC', 'This gigantic dam on the Paraná River generates the most annual electricity of any operating hydroelectric facility in the world, supplying 90% of the electricity consumed by Paraguay and 20% of that consumed by Brazil.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_LARGE_HADRON_COLLIDER', 'Large Hadron Collider', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_LARGE_HADRON_COLLIDER_HELP', '2 Free Technologies. ', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_LARGE_HADRON_COLLIDER_QUOTE', '[NEWLINE][TAB][TAB]"I think it was unwise to over-emphasize that the Higgs boson was seized on as the selling point of the LHC. Physicists know that there is so much more that the machine is going to do. If they don''t find the boson, who''s going to provide the money for anything else?"[NEWLINE][TAB][TAB] - Peter Ware Higgs[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_LARGE_HADRON_COLLIDER_DESC', 'The Large Hadron Collider (LHC) is the world''s largest and highest-energy particle accelerator. Physicists hope that the LHC will help answer some of the fundamental open questions in physics, concerning the basic laws governing the interactions and forces among the elementary objects, the deep structure of space and time, and in particular the intersection of quantum mechanics and general relativity, where current theories and knowledge are unclear or break down altogether. Data is also needed from high energy particle experiments to indicate which versions of scientific models are more likely to be correct and to validate their predictions and allow further theoretical development.[NEWLINE][NEWLINE]The LHC lies in a tunnel 27 kilometres in circumference, as much as 175 metres beneath the Franco-Swiss border near Geneva, Switzerland. This synchrotron is designed to collide opposing particle beams of either protons at an energy of 7 teraelectronvolts (TeV) per particle, or lead nuclei at an energy of 574 TeV per nucleus. The term hadron refers to particles composed of quarks. The Large Hadron Collider was built by the European Organization for Nuclear Research (CERN it was built in collaboration with over 10,000 scientists and engineers from over 100 countries, as well as hundreds of universities and laboratories.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_CHURCHES_LALIBELA', 'Churches of Lalibela', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_CHURCHES_LALIBELA_HELP', 'Provides 25% more faith empire wide. [NEWLINE] Provides faith on nearby hills. ', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_CHURCHES_LALIBELA_QUOTE', '[NEWLINE][TAB][TAB]"We have finished the job, what shall we do with the tools?"[NEWLINE][TAB][TAB] - Halie Selassie[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_CHURCHES_LALIBELA_DESC', 'The Churches of Lalibela are a collection of churches carved from solid rock near the town of Lalibela, in modern day Ethiopia. The area was likely a religious site during the Kingdom of Aksum, a dominant trading partner between Rome and the Indian Ocean, which existed for eight hundred years from 100 to 940 CE. The Aksumites were the first major civilization in the world to adopt Christianity. The religion became the largest faith in the subcontinent, and the Aksumites were likely a factor in its spread throughout Africa.[NEWLINE][NEWLINE]Several churches are laid out in such a way that many people believe them to be an analogy of the holy city of Jerusalem. This has lead to some construction estimates at approximately the conquest of Jerusalem by Saladin in 1197. As such, many of the buildings have names relating to Jerusalem. The town, formerly known as Roha, was renamed after a king of Abysinnia who ruled during the 12th century, which gives more crediability as to the name.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_BANAUE_RICE_TERRACES', 'Banaue Rice Terraces', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_BANAUE_RICE_TERRACES_HELP', 'Provides food on nearby hills [NEWLINE] Must be built on a hill city.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_BANAUE_RICE_TERRACES_QUOTE', '[NEWLINE][TAB][TAB]"Rice is great if you''re really hungry and want to eat two thousand of something. "[NEWLINE][TAB][TAB] - Mitch Hedberg[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_BANAUE_RICE_TERRACES_DESC', 'The rice terraces at Banaue are 2000-year old stepped terraces carved into the mountains of Ifugao in the Philippines. It is commonly thought the terraces were built with minimal equipment, largely by hand. The terraces cover about 4000 square miles of mountainside. They are fed by an ancient irrigation system from the rainforests above the terraces. If the steps are put end to end, they would encircle half the globe.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_PANAMA_CANAL', 'Panama Canal', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_PANAMA_CANAL_HELP', 'Provides increased trade route bonuses. [NEWLINE] Provides +1 Ship movement', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_PANAMA_CANAL_QUOTE', '[NEWLINE][TAB][TAB]"A finer body of men has never been gathered by any nation than the men who have done the work of building the Panama Canal."[NEWLINE][TAB][TAB] - Theodore Roosevelt[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_PANAMA_CANAL_DESC', 'The Panama Canal shortcut made it possible for ships to travel between the Atlantic and Pacific Oceans in half the time previously required. The shorter, faster, safer route to the U.S. West Coast and to nations in and along the Pacific Ocean allowed those places to become more integrated with the world economy.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_HOLLYWOOD', 'Hollywood', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_HOLLYWOOD_HELP', 'Provides 4 free tradeable movies, luxury resources. [NEWLINE] Provides a [ICON_TEAM_7] Free Great Artist.[NEWLINE]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_HOLLYWOOD_QUOTE', '[NEWLINE][TAB][TAB]"Hollywood is a place where they''ll pay you a thousand dollars for a kiss and fifty cents for your soul."[NEWLINE][TAB][TAB] - Marilyn Monroe[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_HOLLYWOOD_PEDIA', 'Hollywood is a district of the city of Los Angeles in the United States. Due to its fame and cultural identity as the historical center of movie studios and movie stars, the word "Hollywood" is often used to represent the American film industry as a whole.[NEWLINE][NEWLINE]The area started life as a idealistic "suburban America", however it quickly grew from 1909, when film-makers started to arrive, and is now synonomous with the American Film Industry. Today, Hollywood is glamourised for being the land of the rich and famous, where dreams are made and wishes come true. It is home to several iconic buildings, including the Hollywood Bowl and Grauman''s Chinese Theatre. However, when most people think of Hollywood, they think of the large sign atop the Hollywood hills. This sign started life as a billboard for the suburban settlement, then named "Hollywoodland". In 1949, the "Land" was removed as part of a renovation contract.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_WAT_PHRA_KAEW', 'Wat Phra Kaew', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_WAT_PHRA_KAEW_HELP', '+10% Gold and Culture from every Shrine and Temple.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_WAT_PHRA_KAEW_QUOTE', '[NEWLINE][TAB][TAB]"If you are respectful by habit, constantly honoring the worthy, four things increase: long life, beauty, happiness, strength."[NEWLINE][TAB][TAB] - Siddhartha Gautama Buddha[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WONDER_WAT_PHRA_KAEW_DESC', 'This majestic temple is regarded as the most sacred Buddhist temple (wat) in Thailand. The main building houses the statue of Emerald Buddha. The legendary history of this Buddha image is traced to India, five centuries after the Lord Buddha attained Nirvana, till it was finally enshrined in Bangkok at the Wat Phra Kaew temple in 1782.[NEWLINE][NEWLINE]Located in the historic centre of Bangkok, within the grounds of the Grand Palace, it enshrines Phra Kaew Morakot (the Emerald Buddha), the highly revered Buddha image meticulously carved from a single block of jade. The Emerald Buddha (Phra Putta Maha Mani Ratana Patimakorn) is a Buddha image in the meditating position in the style of the Lanna school of the north, dating from the 15th century AD.[NEWLINE][NEWLINE]Raised high on a series of platforms, no one is allowed near the Buddha except the King. A seasonal cloak, changed three times a year to correspond to the summer, winter, and rainy season covers the statue. A very important ritual, the changing of the robes is performed only by the King to bring good fortune to the country during each season.[NEWLINE][NEWLINE]The construction of the temple started when King Buddha Yodfa Chulaloke (Rama I) moved the capital from Thonburi to Bangkok in 1785. Unlike other temples, it does not contain living quarters for monks; rather, it has only elaborately decorated holy buildings, statues, and pagodas. The main building is the central ''ubosot'' (ordination hall), which houses the Emerald Buddha.', '', '');


UPDATE LoadedFile SET Value=1 WHERE Type='GEM_Cities.sql';
