--· ES_ES/Cities.sql
/* General */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_GEM_VERSION', 'GEM v1.{1_num}', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_MISSION_START_GOLDENAGE_HELP', 'Esta orden consumirá al Gran Personaje y comenzará una Edad de Oro [ICON_GOLDEN_AGE] (+20% de producción en todas las ciudades) durante {1_Num} turnos. Cada vez que un Gran Personaje comienza una Edad de Oro, la duración se reducirá (hasta un mínimo de 3 turnos).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRADE_ROUTE_INCOME_INFO', '+{1_Num} Oro [ICON_GOLD] por ruta comercial[NEWLINE]+{2_Num} Oro[ICON_GOLD] por ciudadano [ICON_CITIZEN] en la capital[NEWLINE]+{3_Num} Oro [ICON_GOLD] por Ciudadano [ICON_CITIZEN]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_MISSION_HURRY_PRODUCTION_HELP', 'Otorga (200 + 30 * población [ICON_CITIZEN]) Producción [ICON_PRODUCTION] para la construcción actual de la ciudad. Esto consume al Gran Personaje.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_PRODUCTION_BUILDING_ALLOWS_WATER_ROUTES_EXTRA', 'Una ruta comercial [ICON_CONNECTED] de carreteras, ferrocaril o marítima a la Capital produce Oro [ICON_GOLD].[NEWLINE][NEWLINE]Una ruta de ferrocarril [ICON_CONNECTED_RAILROAD] o marítima a la Capital proporciona +25% Producción [ICON_PRODUCTION] (con la tecnología [COLOR_POSITIVE_TEXT]Ferrocarril[ENDCOLOR]).[NEWLINE][NEWLINE]Los [COLOR_POSITIVE_TEXT]Faros[ENDCOLOR] proporcionan una conexión segura entre rutas comerciales marítimas y terrestres.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_IMPROVEMENT_TRADING_POST', 'Villa', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_CIV5_IMPROVEMENTS_TRADING_POST_TEXT', 'Una villa es un grupo de asentamientos o comunidad con una población que oscila entre cientos y varios miles habitantes. Estos pequeños asentamientos se unen a tu sociedad económica.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_CIV5_IMPROVEMENTS_TRADINGPOST', 'Villa', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_GOLD_TRADINGPOST_ADV_QUEST', '¿Proporciona oro la villa?', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_GOLD_TRADINGPOST_HEADING3_BODY', 'Construir una mejora de villa en una casilla para mejorar su rendimiento de oro.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_GOLD_TRADINGPOST_HEADING3_TITLE', 'La Villa', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_WORKERS_TRADINGPOST_HEADING3_BODY', 'La Villa incrementa la producción de oro en 1 en una casilla. No necesita acceso a un recurso.[NEWLINE]Tecnología Necesaria: Caza[NEWLINE]Tiempo de Construcción: 5 turnos[NEWLINE]Puede ser Construida en: Cualquier tipo de tierra, excepto hielo', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_BUILD_TRADING_POST', 'Construir una [LINK=IMPROVEMENT_TRADING_POST]Villa[\LINK]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_BUILD_GOLD_REC', 'Incrementará la cantidad de Oro [ICON_GOLD] producida por esta casilla, ¡aumentando la cantidad de dinero que tendremos para gastar!', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_TP_GOLDEN_AGE_EFFECT', 'Las Ciudades ganan +20% de producción durante Edades de Oro [ICON_GOLDEN_AGE].[NEWLINE]+20% Excedente de alimentos [ICON_FOOD][NEWLINE]+20% Producción [ICON_PRODUCTION][NEWLINE]+20% Oro [ICON_GOLD][NEWLINE]+20% Ciencia [ICON_RESEARCH][NEWLINE]+20% Cultura [ICON_CULTURE][NEWLINE]+20% Fe [ICON_PEACE][NEWLINE][NEWLINE]El excedente de felicidad sigue añadiendose al contador de Edad de Oro mientras estás en una Edad de Oro.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-14'), 'TXT_KEY_BUILDING_MACHU_PICHU_HELP', 'Una montaña cerca de la ciudad gana:[NEWLINE]Alimento: 5 [ICON_FOOD][NEWLINE]Oro: 5 [ICON_GOLD][NEWLINE]Cultura: 5 [ICON_CULTURE][NEWLINE]Fe: 5 [ICON_PEACE]', '', '');
/* Alimento */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_FLOATING_GARDENS_DESC', 'Chinampa', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_FOATING_GARDENS_STRATEGY', 'El Chinampa es el edificio único Azteca, remplaza al Molino de Agua. Incrementa el flujo de alimentos a la ciudad, y solo puede ser construido si la ciudad está cerca de un lago o un río.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_FLOATING_GARDENS_PEDIA', 'Un Chinampa  es una pequeña isla artificial construida en un lago de agua dulce para aumentar la cantidad de tierras disponibles para la agricultura. El lago irriga la isla y la provee con material organico. El resultado es un entorno increiblemente fértil. Los Aztecas eran maestros en este tipo de agriculura, y los ''Jardines Flotantes de Xochimilco'' siguen siendo famosos hoy en día.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_SANITATION_SYSTEM', 'Sistema de Saneamiento', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_SANITATION_SYSTEM_PEDIA', 'El saneamiento es el medio por el que a través de la higiene se mejora la salud y la prevención del contacto humano con los residuos tóxicos.[NEWLINE][NEWLINE]Los residuos pueden ser agentes infecciosos físicos, microbiológicos, biologicos o químicos. LA higiene que se encarga de la prevención puede proporcionarse a través de soluciones de ingeniería (como el alcantarillado o el tratamiento de aguas residuales), tecnologías simples (letrinas, tanques sépticos), o incluso con prácticas personales de higiene (lavándose las manos con jabón).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_VACCINATIONS', 'Vacunas', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_VACCINATIONS_PEDIA', 'Una vacuna es el preparado biológico que mejora la inmunidad a un tipo particular de enfermedad. La vacuna estimula el sistema inmunitario del cuerpo para reconocer un agente de enfermedad, destruirlo y "recordarlo", por lo que el sistema inmune puede reconocer y destruir más facilmente cualquiera de esos microorganismos en posteriores encuentros. La Vacunación es el método más efectivo en prevención de enfermerdades infecciosas.[NEWLINE][NEWLINE]El esfuerzo global de la humanidad en la vacunación erradicó la viruela, y restringió otras enfermedades mortales como la polio, sarampión, y tétano. La Viruela mató aproximadamente un 90% delos Nativos Americanos después del contacto con Eurasia en los 1500s. Cuando finalmente fue erradicada en 1979, la viruale había matado aproximadamente 300–500 millones de personas en el mundo tan solo en el pasado siglo, más que todas las guerras del siglo 20 juntas. La Viruela fue la primera enfermedad para la que se produjo una vacuna en 1796. La inmunización fue llamada vacuna porque ésta derivaba de un virus que afectaba a las vacas (Latin: vacca - vaca).', '', '');
/* Producción */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_WORKSHOP_STRATEGY', 'El Taller incrementa la producción cuando construyes edificios. Las Ciudades en colinas no pueden construir talleres.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_STABLE_STRATEGY', 'El Establo incrementa la velocidad de producción de las unidades montadas y añade producción por ciertos recursos.', '', '');
/* Oro */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_MINT_STRATEGY', 'La Ceca incrementa los ingresos de Oro [ICON_GOLD] de la Ciudad y los ingresos de oro por ciertos productos.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_WAREHOUSE', 'Almacén', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-15'), 'TXT_KEY_BUILDING_WAREHOUSE_PEDIA', 'Un Almacén es un edificio comercial para el almacenamiento de mercancías. Los Almacenes son usados por los fabricantes, importadores, exportadores, distribuidores, transportistas, clientes, etc. Las mercancías almacenadas abarcan cualquier tipo de materia prima, materiales empaquetados, repuestos, componentses, o bienes manufacturados asociados con la agricultura, fabricación, o comercio.', '', '');
/* Ciencia */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_MENTORS_HALL', 'Sala de Mentores', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_MENTORS_HALL_PEDIA', 'La Mentoría es un proceso organizado para la transmisión de conocimientos, capital social y el apoyo psicosocial del mentor al discípulo para objetivos laborales o desarrollo profesional. La Mentoría se basa en una comunicación informal, normalmente cara a cara, y durante un periodo de tiempo sostenido entre una persona reconocida por tenern un gran conocimiento, sabiduría o experiencia (el mentor) y una persona que desea aprender de él (el discípulo).', '', '');
/* Cultura */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_RADIO_STATION', 'Estación de Radio', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_RADIO_STATION_PEDIA', 'La radiodifusión es una transmisión sin cables de una sola dirección a través de ondas de radio con la intención de alcanzar una amplia audiencia.[NEWLINE][NEWLINE]Las primeras estaciones de radio eran simples sistemas de telégrafo y no transmitían audio. En los inicios de 1920s, las primeras estaciones de audio fueron establecidas por equipos radiofónicos de fabricantes y minoristas que ofrecían programas de radio con la intención de vender radios a los oyentes.[NEWLINE][NEWLINE]Cuando la práctica de la publicidad se popularizó, cada programa de radio era normalmente patrocinado por negocios particulares a cambio de una breve mención del nombre de su empresa al inicio y al final del programa patrocinado. Sin embargo, los dueños de las estaciones de radio pronto se dieron cuenta de que podían ganar más dinero vendiendo los derechos de patrocinio en pequeños márgenes de tiempo durante las emisiones de su estación de radio, mucho más que vendiendo los derechos de patrocinio a un único negocio por programa.', '', '');
/* Felicidad */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_STONE_WORKS_STRATEGY', 'Las Canteras solo pueden construirse en una ciudad cerca de un un recurso mejorado de Piedra [ICON_RES_STONE] o Mármol [ICON_RES_MARBLE]. Las Canteras incrementan la producción [ICON_PRODUCTION] de la ciudad.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_ARENA', 'Arena', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_ARENA_PEDIA', 'Una Arena es un area cerrada, normalmente circular o con forma de óvalo, frecuentemente diseñado para eventos y espectáculos deportivos. La palabra deriva del Latín harena, se utilizaba una arena particularmente fina para absorber la sangre en las antiguas arenas como los coliseos en Roma.[NEWLINE][NEWLINE]Las Arenas están compuestas por un gran espacio abierto rodeado por todos o la mayoría de sus lados por varios niveles de asientos para los espectadores. La clave principal de una arena es que el espacio para el evento se encuentra en el punto más bajo, permitiendo una maxima visibilidad. Una Arena está normalmente diseñada para acomodar un enorme número de espectadores.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_PUBLISHING_HOUSE', 'Editorial', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_PUBLISHING_HOUSE_PEDIA', 'La Publicación es la actividad de hacer pública la información al público general. En algunos casos, los autores pueden ser sus propios editores, lo que significa que los autores del contenido también proveen a los medios entregando y mostrando el contenido por igual.[NEWLINE][NEWLINE]Tradicionalmente, el término se refiere a la distribución de trabajos escritos como los libros y revistas. Con la aparición de los sistemas de información digital e Internet, el alcance de la publicación se expandió para incluir los recursos electrónicos, como las versiones electrónicas de libros y publicaciones periódicas, además de micgropublicaciones, websites blogs, publicaciones de videojuegos y similares.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_CINEMA', 'Cine', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_CINEMA_PEDIA', 'Una Sala de Cine es un lugar para ver películas.[NEWLINE][NEWLINE]La mayoría aunque no todos los cines son operaciones comerciales dirigidas al público general, que asiste mediante la compra de una entrada. La película se proyecta con un proyector de películas en una gran pantalla enfrente de la sala. La mayoría de las salas de cine estan equipadas hoy en día con proyectores digitales, eliminando la necesidad del transporte físico de la cinta.', '', '');
/* Otros */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_SUPERMAX_PRISON', 'Prisión Máxima Seguridad', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_SUPERMAX_PRISON_PEDIA', 'Prisión de Máxima Seguridad es el nombre usado para describir prisiones de "unidad de control", o unidades sin prisiones, lo que representa los máximos niveles de seguridad en custodia en sistemas penales de algunos países. El obejtivo es proporcionar a largo plazo la segregación residencial de los reclusos clasificados como de alto riesgo en el sistema penitenciario - los criminales "lo peor de lo peor" y aquellos que suponen una amenaza para la seguridad nacional e internacional.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_CAPITAL_BUILDING', 'Capital', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_CAPITAL_BUILDING_PEDIA', 'La sede del gobierno is el edificio, complejo de edificios o ciudadr city desde donde el gobierno ejerce su autoridad. La sede del gobierno, se encuentra normalmente en la capital. Sin embargo, en algunos países la sede del gobierno difiere de la capital. por ejemplo en Holada donde la Haya es la sede del gobierno y Amsterdan es la capital jurídica de Holanda. En la mayoría, suele ser la misma ciudad, por ejemplo, Moscú es la capital y sede de gobierno de Rusia. En el Reino Unido, la sede de gobierno es Londres, la capital, o más específicamente la Ciudad de Westminster.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_GREAT_HALL', 'Ayuntamiento', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-18'), 'TXT_KEY_BUILDING_GREAT_HALL_PEDIA', 'El Ayuntamiento es el edificio administrativo del jefe de una ciudad, pueblo u otro municipio. Normalmente alberga el consejo, sus departamentos asociados y sus empleados de la ciudad o pueblo. También por lo general funciona como la base del alcalde de una ciudad, pueblo, ciudad, provincia o región.[NEWLINE][NEWLINE]El gobierno local puede tratar de utilizar el edificio de ayuntamiento para promover y mejorar la calidad de vida de la comunidad. En muchos casos, los "''ayuntamientos'' sirven, no solo de edificios para el gobierno, sino también como instalaciones para varias actividades cívicas y culturaless. Estos pueden incluir exposiciones de arte, representaciones teatrales, exposiciones y festivales. Como símbolos de gobierno local, los ayuntamientos de la ciudad suelen tener una arquitectura distintiva, y los edificios pueden tener un gran significado histórico.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_PALACE', 'Palacio', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_BUILDING_PALACE_PEDIA', 'Un palacio es una gran residencia, especialmente una residencia real o la casa de un jefe de Estado o de algún otro dignatario de alto rango, como un obispo o arzobispo.[NEWLINE][NEWLINE]La palabra deriva del nombre latino Palatium, del Monte Palatino, una de las siete colinas de Roma. En muchas partes de Europa, el término también se aplica a los ambiciosos mansiones privadas de la aristocracia. Muchos palacios históricos están ahora sometidos a otros usos, como parlamentos, museos, hoteles o edificios de oficinas. La palabra también se usa a veces para describir un edificio ricamente ornamentado utilizado para espectáculos públicos o exhibiciones.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-16'), 'TXT_KEY_POPUP_CITY_CAPTURE_INFO', '¿Qué quieres hacer con esta Ciudad?', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-18'), 'TXT_KEY_POPUP_ANNEX_PUPPET', '[ICON_OCCUPIED] [COLOR_POSITIVE_TEXT]Anexionar[ENDCOLOR]: Mejor para las grandes ciudades. La construcción de una Delegación la convierte en una ciudad normal .[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Hacer Títere[ENDCOLOR][ICON_PUPPET]: Mejor para ciudades pequeñas. Los títeres tienen 3 de Infelicidad [ICON_HAPPINESS_4] básicos por ciudad (en vez de 4) y no incrementa los costes de Políticas.[NEWLINE][NEWLINE]Las ciudades Ocupadas y Títeres producen menos rendimiento que una ciudad normal.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-18'), 'TXT_KEY_POPUP_ANNEX_CITY', 'Anexionar la Ciudad', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-18'), 'TXT_KEY_POPUP_CITY_CAPTURE_INFO_PUPPET', 'Puedes Anexionar [ICON_OCCUPIED] una ciudad Títere en cualquier momento.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-18'), 'TXT_KEY_CIV5_BABYLON_WALLS_STRATEGY', 'Las Murallas de Babilonia son el Edificio Único de Babilonia, remplaza las murallas normales. Las Murallas de Babilonia incrementan la fuerza defensiva de la ciudad y puntos de golpe de la ciudad (ambas considerablemente superiores a las de las murallas normales) .', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-18'), 'TXT_KEY_BUILDING_WALLS_STRATEGY', 'Las Murallas incrementan la fuerza defensiva de la ciudad y puntos de golpe, haciéndola más difícil de conquistar. Las Murallas son muy útiles para ciudades situadas en las fronteras de la civilización.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-18'), 'TXT_KEY_BUILDING_MILITARY_BASE_STRATEGY', 'La Base Militar es un edificio de mitad del juego que aumenta la fuerza defensiva de la ciudad y sus puntos de golpe. La ciudad debe poseer un Arsenal antes de que la Base Militar se pueda construir', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-18'), 'TXT_KEY_BUILDING_CASTLE_STRATEGY', 'El castillo es un edificio de la época medieval que aumenta la fuerza defensiva de la ciudad y sus puntos de golpe. La ciudad debe poseer una Muralla antes de que el Castillo se pueda construir.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-18'), 'TXT_KEY_BUILDING_ARSENAL_STRATEGY', 'El Arsenal es un edificio militar de mitad del juego que aumenta la fuerza defensiva y puntos de vida de una ciudad, haciendo que la ciudad sea más difícil de capturar. La ciudad debe poseer un Castillo antes de que se pueda construir un Arsenal.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-18'), 'TXT_KEY_BUILDING_MUGHAL_FORT_STRATEGY', 'El Fuerte mogol es un edificio de la época medieval en que aumenta la fuerza defensiva de la ciudad, puntos de golpe, y proporciona Cultura [ICON_CULTURE] cada turno. Es el edificio único de India, y remplaza el Castillo. Tras descubrir de descubrir el Vuelo, proporcionará también un bonus de Oro [ICON_GOLD] a la Ciudad. Las Murallas son un prerequisito para construir el Fuerte Mogol.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-18'), 'TXT_KEY_BUILDING_GARDEN_STRATEGY', 'El Jardín aumenta la velocidad a la que se generan Grandes Personajes [ICON_GREAT_PEOPLE] en la ciudad.', '', '');
/* Maravillas Nacionales */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_HEROIC_EPIC_HELP', 'Todas las nuevas unidades entrenadas en esta Ciudad reciben la promoción [COLOR_POSITIVE_TEXT]Moral[ENDCOLOR], la cual mejora la fuerza de combate [ICON_STRENGTH] un 15%.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_OXFORD_UNIVERSITY', 'Universidad de Heidelberg', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_HOLY_PALACE', 'Palacio Sagrado', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_HOLY_PALACE_HELP', 'Proporciona +8 [ICON_FAITH] Fé y 25% de Fé en la ciudad que se construya.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_HOLY_PALACE_STRATEGY', 'El Palacio Sagrado provee un aumento significativo en la [ICON_FAITH] fé de la ciudad.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_HOLY_PALACE_PEDIA', 'Todo', '', '');
/* Maravillas */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-18'), 'TXT_KEY_PROMOTION_PANAMA_CANAL', 'Canal de Panamá', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_PROMOTION_PANAMA_CANAL_HELP', '+1 Movimiento [ICON_MOVES] para unidades Navales', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_PROMOTION_PARTHENON', 'Partenón', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_PROMOTION_PARTHENON_HELP', '+10% de Fuerza [ICON_STRENGTH] para los Grandes Generales y Almirantes', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_GREATWALL_DESC', 'La Gran Muralla china es una de las más grande y famosas construcciones del mundo. Los gobernantes chinos la construyeron para repeler los ataques de los nómadas que vivían en las actuales regiones de Manchuria y Mongolia. Es interesante resaltar que la Gran Muralla no se construyó para mantener a raya a los nómadas (los chinos sabían que era poco menos que imposible proteger una frontera tan larga como la suya) sino para que les fuera más difícil llevarse el botín y, por consiguiente, las incursiones fueran menos provechosas y menos atractivas.[NEWLINE][NEWLINE]En realidad, existen cinco "grandes murallas", cada una de las cuales fue levantada por una dinastía diferente. Las primeras cuatro estaban hechas de tierra, así que prácticamente han desaparecido. La actual fue construida casi enteramente por la Dinastía Ming entre los años 1368 y 1640 d. C. Esta muralla se construyó a mayor escala y usando materiales más duraderos. La muralla Ming se extiende a lo largo de más de 6.000 kilómetros, desde el paso de Shanhai en el golfo de Bohai (al este) a Lup Nur, en la parte sureste de la región autónoma de Uygur en Xinjiang (al oeste). Ésta era la región por la que la ruta de la seda entraba en China, y estaba protegida por una serie de torres que podían comunicarse con señales de humo y transmitir rápidamente mensajes a lo largo de la vasta muralla.[NEWLINE][NEWLINE]En términos puramente militares, la Gran Muralla puede considerarse un intento más o menos fallido. Los manchúes sobornaron a un general chino para que les franqueara el paso, por lo que, a la hora de detener un ataque bárbaro de primera magnitud, no sirvió de mucho. Después de que los manchúes conquistaran China, las fronteras del país se extendieron más en dirección norte, por lo que la existencia de la muralla se volvió irrelevante. El coste de su construcción en términos monetarios fue enorme y se calcula que, en términos humanos, pudo haber excedido el millón de almas (a veces se la ha bautizado también como "el gran cementerio").[NEWLINE][NEWLINE]En nuestros días, la mayor parte de la muralla se encuentra en estado de abandono. Aunque las zonas más turísticas están en buen estado, el resto se encuentra en ruinas. Se calcula que solo el 20% está en buenas condiciones. A pesar de todo, la Gran Muralla sigue siendo una de las principales atracciones turísticas de China y una de las auténticas maravillas del mundo.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_PENTAGON_HELP', 'Todas las unidades se curan cada turno.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_STATUE_ZEUS', 'Partenón', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_STATUE_ZEUS_HELP', 'Incrementa el poder de los Grandes Generales. [NEWLINE] Genera un Gran General [ICON_TEAM_7].', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_STATUE_ZEUS_QUOTE', '[NEWLINE][TAB][TAB]"Entrando en el templo que llaman Partenón, todo lo que está llamado frontón hace referencia al nacimiento de Atenea, mientras que en la parte posterior está la disputa de Poseidón con Antenea por la tierra."[NEWLINE][TAB][TAB] - Pausanias (Descripción de Grecia, I, 24, 5)[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_STATUE_ZEUS_DESC', 'El Partenón es un templo en la Acrópolis de Atenas dedicado a la diosa griega Atenea, a quien el pueblo de Atenas consideraban su protectora. Fue construido durante el tiempo que Atenas era la potencia militar y comercial del Mediterráneo. Es el edificio más importante que ha sobrevivido de la Grecia clásica, generalmente considerado como la culminación del desarrollo del orden dórico. Sus esculturas decorativas se consideran algunas de las cumbres del arte griego. El Partenón es considerado como un símbolo duradero de la antigua Grecia y de la democracia ateniense y uno de los más grandes monumentos culturales del mundos. [NEWLINE] [NEWLINE] Su construcción se inició en el año 447 aC y se terminó en el año 438 aC, aunque las decoración del Partenón continuó hasta 432 antes de Cristo. El propio Partenón sustituyó a un templo más antiguo de Atenea que los historiadores llaman el Pre-Partenón o Antiguo Partenón, que fue destruido en la invasión persa del año 480 AC. Al igual que la mayoría de los templos griegos, el Partenón fue utilizado como tesorería. Durante un tiempo, sirvió como el banco de la Liga de Delos, que más tarde se convirtió en el Imperio ateniense. [NEWLINE] [NEWLINE] El primer intento de construir un santuario para Atenea Parthenos en el sitio de la actual Partenón se inició poco después de la Batalla de Marathon (490-488 aC), sobre una base de piedra caliza que extiende y nivela la parte sur de la cumbre de la Acrópolis. A mitad del siglo 5º, cuando Atenas fue el mayor centro cultural de su época, Pericles inició un ambicioso proyecto de construcción que duró toda la segunda mitad del siglo. Los edificios más importantes se ven en la actualidad. La Acrópolis, el Partenón, los Propileos, el Erecteion y el templo de Atenea Niké, se construyeron durante este período. El Partenón fue construido bajo la supervisión general del escultor Fidias, que también estaba a cargo de la decoración, y los arquitectos fueron Ictino y Kallikrates. [NEWLINE] [NEWLINE] En el siglo 5º, el Partenón fue convertido en iglesia cristiana dedicada a la Virgen María. Después de la conquista turco-otomana, fue convertido en una mezquita a principios de la década de 1460, y había un minarete construido en él. El 26 de septiembre de 1687, un depósito de municiones turco-otomano en el interior del edificio fue encendido por un bombardeo veneciano. La explosión dañó severamente el Partenón y sus esculturas. En 1806, Thomas Bruce, un noble británico y diplomático, retiró algunas de las esculturas supervivientes, con el permiso de los turcos. Estas esculturas, ahora conocidos como los mármoles de Elgin o los Mármoles del Partenón, se vendieron en 1816 al Museo Británico en Londres, donde se muestran ahora.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_LEANING_TOWER', 'Duomo', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_LEANING_TOWER_QUOTE', '[NEWLINE][TAB][TAB]"El Renacimiento del siglo XV era, amenudo, mejor por lo que se diseñó que por lo que se logró."[NEWLINE][TAB][TAB] - Walter Pater[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_LEANING_TOWER_DESC', 'El Duomo (Basilica di Santa María del fiore) es una gran catedral situada en el corazón de Florencia, Italia. Le tomó 140 años para construirse, terminando en 1436. Durante la construcción, Florencia era una república, que formaba parte de muchas ciudades-estado italianas. La Catedral ha jugado un papel central en la república y se dice que comenzó el Renacimiento.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_HUBBLE', 'Laboratorios Bell', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_HUBBLE_QUOTE', '[NEWLINE][TAB][TAB]"Un instituto de tecnología creativa requiere una gran cantidad de personas con talento para promover un intercambio de ideas continuo."[NEWLINE][TAB][TAB] - Mervin Kelly, presidente de Laboratorios Bell[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_HUBBLE_DESC', 'Esta institución de investigación revolucionó el mundo al inventar los componentes fundamentales de las computadoras modernas, como la más importante maravilla de la ingeniería del siglo 20: los transistores. Estos dispositivos permitió reducir el tamaño de los ordenadores desde las proporciones de una casa a tamaño bolsillo a la vez que aumentó drásticamente su capacidad.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_MAUSOLEUM_HALICARNASSUS', 'Anfiteatro Flavio', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_MAUSOLEUM_HALICARNASSUS_DESC', 'Comúnmente conocido como * El Coliseo *, este anfiteatro elíptico en el centro de la ciudad de Roma es el más grande jamás construido en el Imperio Romano. Es considerado una de las más grandes obras de la arquitectura e ingeniería romana. [NEWLINE] [NEWLINE] Con una ubicación justo al este del Foro Romano, su construcción se inició en el 72 dC bajo el mandato del emperador Vespasiano y fue terminado en el año 80 dC bajo el de Tito, añadiendo posteriores modificaciones que se hicieron durante el reinado de Domiciano (81-96 dC). El nombre de Anfiteatro Flavio se debe a los apellidos tanto de Vespasiano como de Tito (Flavius​​, de la casa Flavia). [NEWLINE] [NEWLINE] Con una capacidad de asientos de 50.000 espectadores, el Coliseo fue utilizado para combates de gladiadores y espectáculos públicos tales como simulacros de batallas navales, caza de animales, ejecuciones, recreaciones de famosas batallas y obras de teatro basadas en la mitología clásica. El edificio dejó de ser utilizado para el entretenimiento en la primera época medieval. Fue reutilizado posteriormente para fines tales como la vivienda, talleres, cuartos para una orden religiosa, fortaleza, cantera y santuario cristiano. [NEWLINE] [NEWLINE] Se ha creido durante mucho tiempo que el nombre de Coliseo deriva de la cercana colosal estatua de Nero. Esta estatua fue posteriormente remodelada por los sucesores de Nero en semejanza de Helios o Apolo, el dios del sol, mediante la adición de la correspondiente corona solar. La cabeza de Nero también fue sustituida varias veces con la de los emperadores de grandes éxitos. El coloso finalmente cayó. Posiblemente, derribado para reutilizar su bronce. Para el año 1000 el nombre de Coliseo había sido acuñado para referirse al anfiteatro. La estatua en sí fue olvidada en gran parte y sólo sobrevive su base, situada entre el Coliseo y el Templo cercano de Venus y Roma.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_MAUSOLEUM_HALICARNASSUS_QUOTE', '[NEWLINE][TAB][TAB]"¿Qué voy a decir sobre ese lugar espantoso, el anfiteatro? Incluso el perjurio no podría definirlo. Para ello se le dedican más nombres, y los nombres más horrible, que el propio Capitolio, es el templo de todos los demonios. Hay más espíritus inmundos reunidos allí que hombres pueden sentarse."[NEWLINE][TAB][TAB] - Tertuliano (De Spectaculis, XII)[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_HAGIA_SOPHIA_HELP', '+1 [ICON_HAPPINES][NEWLINE]+3 [ICON_CULTURE][NEWLINE]+1 [ICON_FAITH][NEWLINE]1 espacio para un Artista', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_ITAIPU_DAM', 'Represa de Itapú', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_ITAIPU_DAM_HELP', 'Proporciona producción en todas las ciudades. [NEWLINE]Proporciona un Gran Ingeniero gratis. [NEWLINE]Ofrece una Central Hidráulica en la ciudad. [NEWLINE]Tiene que ser construida sobre un río.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_ITAIPU_DAM_QUOTE', '[NEWLINE][TAB][TAB]"Las mujeres piensan que un ingeniero es un hombre con botas altas construyendo una presa. Ellas no se dan cuenta de que el 95% de la ingeniería se hace en una bonita oficina con aire acondicionado."[NEWLINE][TAB][TAB] - Beatrice Alice Hicks, la primera mujer ingeniero en Western Electric.[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_ITAIPU_DAM_DESC', 'Esta gigantesca presa en el río Paraná genera más electricidad al año que cualquier instalación hidroeléctrica del mundo, suministrando el 90% de la electricidad consumida en Paraguay y el 20% de la consumida por Brasil.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_LARGE_HADRON_COLLIDER', 'Gran Colisionador de Hadrones', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_LARGE_HADRON_COLLIDER_HELP', '2 Tecnologías gratis. ', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_LARGE_HADRON_COLLIDER_QUOTE', '[NEWLINE][TAB][TAB]"Creo que era imprudente insistir demasiado en que el bosón de Higgs era el único objetivo del LHC. Los físicos saben que hay muchas más cosas que la máquina puede hacer. Si no encuentran el bosón, ¿quién les iba a proporcionar el dinero para algo más?"[NEWLINE][TAB][TAB] - Peter Ware Higgs[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_LARGE_HADRON_COLLIDER_DESC', 'El Gran Colisionador de Hadrones (LHC) es el acelerador de partículas más grande del mundo. Los físicos esperan que el LHC ayudará a responder algunas de las preguntas sin responder fundamentales de la física, en relación con las leyes básicas que rigen las interacciones y las fuerzas entre los objetos elementales, la estructura profunda del espacio y el tiempo, y en particular la intersección de la mecánica cuántica y la relatividad general , donde las actuales teorías y conocimientos son poco claras o discrepan entre sí. Los datos de la energía de partículas también se necesitan en experimentos para indicar qué versiones de los modelos científicos tienen más probabilidades de ser correctas y para validar sus predicciones y permitir un mayor desarrollo teórico. [NEWLINE] [NEWLINE] El LHC se encuentra en un túnel de 27 kilómetros de circunferencia, a 175 metros por debajo de la frontera franco-suiza, cerca de Ginebra, Suiza. Este sincrotrón está diseñado para chocar haces opuestos de partículas, ambos de protones a una energía de 7 teraelectronvoltios (TeV) por partícula, o conducir núcleos a una energía de 574 TeV por núcleo. Los hadrones son partículas compuestas de quarks. El Gran Colisionador de Hadrones, construido por la Organización Europea para la Investigación Nuclear (CERN) fue construido en colaboración con más de 10.000 científicos e ingenieros de más de 100 países, así como cientos de universidades y laboratorios.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_CHURCHES_LALIBELA', 'Iglesias de Lalibela', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_CHURCHES_LALIBELA_HELP', 'Proporciona 25% más de Fé [ICON_FAITH]. [NEWLINE] Proporciona Fé en las colinas cercanas. ', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_CHURCHES_LALIBELA_QUOTE', '[NEWLINE][TAB][TAB]"Hemos terminado la tarea, ¿qué vamos a hacer con las herramientas?"[NEWLINE][TAB][TAB] - Halie Selassie[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_CHURCHES_LALIBELA_DESC', 'Las iglesias de Lalibela son un conjunto de iglesias excavadas en la roca cerca de la ciudad de Lalibela, en la actual Etiopía. La zona era probablemente un lugar de culto durante el reino de Aksum, un socio comercial dominante entre Roma y el Océano Índico, que existió durante 800 años desde el 100 dC al 940 dC. Los aksumitas fueron la primera civilización importante en el mundo en adoptar el cristianismo. La religión se convirtió en la fe mayoritaria en el subcontinente, y los aksumitas fueron un importante factor en su difusión a través de África. [NEWLINE] [NEWLINE] Varias iglesias están dispuestas de tal manera que muchas personas creen que son una analogía de la sagrada ciudad de Jerusalén. Esto ha llevado a algunos a estimar su construcción aproximadamente en la conquista de Jerusalén por Saladino en 1197. Como tal, muchos de los edificios tienen nombres relacionados con Jerusalén. La ciudad, antes conocida como Roha, recibió el nombre de un rey de Abisinia, que gobernó durante el siglo 12, lo que le dio aún más renombre.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_BANAUE_RICE_TERRACES', 'Terrazas de Arroz de Banaue', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_BANAUE_RICE_TERRACES_HELP', 'Proporciona alimento [ICON_FOOD] en las colinas cercanas [NEWLINE] La ciudad debe estar contruida en una colina.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_BANAUE_RICE_TERRACES_QUOTE', '[NEWLINE][TAB][TAB]"El arroz es genial si estás hambriento y quieres comer dos mil de algo. "[NEWLINE][TAB][TAB] - Mitch Hedberg[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_BANAUE_RICE_TERRACES_DESC', 'Las terrazas de arroz de Banaue son antiguas terrazas de 2000 años de antiguedad escalonadas y excavadas en las montañas de Ifugao en Filipinas. Comúmnemente se piensa que las terrazas fueron construidas con un equipo mínimo, en gran parte a mano. Las terrazas cubren unos 4000 kilómetros cuadrados de ladera. Estos son alimentados por un sistema de riego antiguo desde bosques tropicales sobre de las terrazas. Si los escalones se colocaran de extremo a extremo, rodearían la mitad del globo.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_PANAMA_CANAL', 'Canal de Panamá', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_PANAMA_CANAL_HELP', 'Incrementa los bonus de las rutas comerciales. [NEWLINE] Proporciona +1 Movimiento [ICON_MOVES] a unidades navales', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_PANAMA_CANAL_QUOTE', '[NEWLINE][TAB][TAB]"Nunca se ha reunido por ninguna nación un grupo de hombres equiparable a los hombres que han hecho el trabajo de construir el Canal de Panamá."[NEWLINE][TAB][TAB] - Theodore Roosevelt[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_PANAMA_CANAL_DESC', 'El acceso directo Canal de Panamá ha permitido a los buques viajar entre los océanos Atlántico y Pacífico en la mitad del tiempo requerido anteriormente. La ruta más corta, más rápida, más segura a la Costa Oeste de los EE.UU. y a las naciones a lo largo del Océano Pacífico permitiendo a esos lugares que se integren en la economía mundial.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_HOLLYWOOD', 'Hollywood', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_HOLLYWOOD_HELP', 'Proporciona 4 películas comerciales gratis, recurso de lujo. [NEWLINE] Proporciona 1 Gran Artista [ICON_TEAM_7] gratis.[NEWLINE]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_HOLLYWOOD_QUOTE', '[NEWLINE][TAB][TAB]"Hollywood es un lugar donde pagan mil dólares por un beso y cincuenta centavos por tu alma."[NEWLINE][TAB][TAB] - Marilyn Monroe[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_HOLLYWOOD_PEDIA', 'Hollywood es un distrito de la ciudad de Los Ángeles en los Estados Unidos. Debido a su fama y la identidad cultural como el centro histórico de estudios de cine y estrellas de cine, la palabra ''Hollywood'' se utiliza a menudo para representar a la industria cinematográfica norteamericana en su conjunto. [NEWLINE] [NEWLINE] El área comenzó su vida como una idealizada ''América suburbana'', sin embargo, creció rápidamente a partir de 1909, cuando los cineastas comenzaron a llegar y ahora es sinónimo de la industria cinematográfica estadounidense. Hoy en día, Hollywood está idealizada por ser la tierra de los ricos y famosos, donde los sueños y deseos se hacen realidad. Es el hogar de varios edificios emblemáticos, como el Hollywood Bowl y Teatro Chino de Grauman. Sin embargo, cuando la mayoría de la gente piensa en Hollywood, piensan en el gran letrero encima de las colinas de Hollywood. Esta muestra comenzó su vida como una valla publicitaria para las cercanías, entonces llamado "Hollywoodland". En 1949, el "Land" fue eliminado como parte de un contrato de renovación.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_BUILDING_WAT_PHRA_KAEW', 'Templo del Buda de Esmeralda', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_WAT_PHRA_KAEW_HELP', '+10% de Oro [ICON_GOLD] y Cultura [ICON_CULTURE] por cada santuario y templo.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_WAT_PHRA_KAEW_QUOTE', '[NEWLINE][TAB][TAB]"Si eres respetuoso habitualmente y honras constantemente a tus ancestros, cuatro cosas mejoraran: larga vida, belleza, felicidad, fuerza."[NEWLINE][TAB][TAB] - Siddhartha Gautama Buda[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-20'), 'TXT_KEY_WONDER_WAT_PHRA_KAEW_DESC', 'Este majestuoso templo es considerado como el más sagrado templo budista (wat) en Tailandia. El edificio principal alberga la estatua de Buda de Esmeralda. La legendaria historia de esta imagen de Buda se remonta a la India, cinco siglos después de que el Señor Buda alcanzara el Nirvana, hasta que finalmente se consagró en Bangkok en el templo Esmeralda de Buda (Wat Phra Kaew) en 1782. [NEWLINE] [NEWLINE] Se ubica en el centro histórico de Bangkok , dentro de los terrenos del Gran Palacio, que consagra Phra Kaew Morakot (el Buda Esmeralda), la muy venerada imagen de Buda meticulosamente tallada en un solo bloque de jade. El Buda Esmeralda (Phra Maha Mani Putta Ratana Patimakorn) es una imagen de Buda en la posición de meditación en el estilo de la escuela Lanna del norte, que data del siglo 15. [NEWLINE] [NEWLINE] Levantada sobre una serie de plataformas , no se permite a nadie acercarse al Buda, excepto al Rey. Un manto de temporada, que se cambia tres veces al año para verano, el invierno y la temporada de lluvias, cubre la estatua. Un ritual muy importante, el cambio de los hábitos que se realiza sólo por el rey para traer buena fortuna al país durante cada temporada. [NEWLINE] [NEWLINE] La construcción del templo comenzó cuando el rey Buda Yodfa Chulaloke (Rama I) trasladó la capital de Thonburi de Bangkok en 1785. A diferencia de otros templos, no contiene viviendas para los monjes, tan solo tiene edificios sagrados, estatuas y pagodas elaboradamente decorados. El edificio principal es el ''Ubosot'' central (salón de ordenación), que alberga el Buda Esmeralda.', '', '');


UPDATE LoadedFile SET Value=1 WHERE Type='GEM_Cities.sql';
