--· ES_ES/Diplomacy.sql
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_DISCUSS_MESSAGE_DEC_FRIENDSHIP_TT', 'Doubla los ingresos procedentes de [ICON_RESEARCH] Acuerdos de Investigación y [ICON_GOLD] Aperturas de Fronteras Mutuo con este líder. [NEWLINE][NEWLINE]Una alianza promueve la diplomacia amistosa y disuade a los agresores externos. Los aliados pueden solicitar asistencia economica o diplomática, y la falta de apoyo a tu aliado puede enfadarlos', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_OPEN_BORDERS_TT', 'Con [COLOR_YIELD_GOLD]apertura de fronteras mutuo[/COLOR], 1% de la producción combinada [ICON_GOLD] Ingresos de ambos jugadores se añade a tus ingresos de oro (2% para países Aliados).[NEWLINE][NEWLINE] Permite a las unidades del otro jugador pasar a través de tu territorio.[NEWLINE][NEWLINE](Dura {1_Num} turnos.)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_NOTIFICATION_MINOR_BARB_KILLED', '¡Has acabado con los Barbaros cerca de {1_CivName:textkey}! Te están muy agradecidos. ¡Has ganado +15[ICON_INFLUENCE] Influencia con ellos!', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_NTFN_RA_FREE_TECH', 'Tu Acuerdo de Investigación con {1_CivName:textkey} ha terminado.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_PEACE_TREATY', 'TRATADO DE PAZ (20 turns)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_PEACE_TREATY_TURNS', 'TRATADO DE PAZ (20 turns)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_ALLOW_EMBASSY_NO_TECH_PLAYER', '[NEWLINE][NEWLINE]No tienes la Tecnología necesaria para establecer una embajada (Comercio).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_ALLOW_EMBASSY_NO_TECH_OTHER_PLAYER', '[NEWLINE][NEWLINE]Ellos no tienen la Tecnología necesaria para establecer una embajada (Comercio).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_OPEN_BORDERS_NO_TECH', '[NEWLINE][NEWLINE]Ninguno de los jugadores tienen la tecnología necesaria para completar este acuerdo (Moneda).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_DEF_PACT_NO_TECH', '[NEWLINE][NEWLINE]Ninguno de los jugadores tienen la tecnología necesaria para completar este acuerdo (Gremios).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_RESCH_AGREEMENT_NO_TECH', '[NEWLINE][NEWLINE]Ninguno de los jugadores tienen la tecnología necesaria para completar este acuerdo (Filosofía).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_BORDER_AGREEMENT', '[COLOR_YIELD_GOLD]Apertura de Fronteras Mutuas[ENDCOLOR][NEWLINE]1% de los ingresos combinados de ambos jugadores se añaden a tu [ICON_GOLD] Tasa de Oro (2% para países Aliados).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_BORDERS_YES_TT', '[COLOR_YIELD_GOLD]Proponer Apertura de Fronteras Mutuas[ENDCOLOR][NEWLINE1% de los ingresos combinados de ambos jugadores se añaden a tu [ICON_GOLD] Tasa de Oro (2% si estáis Aliados).[NEWLINE][NEWLINE]Dura {1_num} turnos.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_BORDERS_NO_TT', ' Apertura de Fronteras Mutuas activa.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_BORDERS_US_TT', 'Nos abren sus fronteras.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_BORDERS_THEM_TT', 'Les abrimos nuestras fronteras.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_RESEARCH_AGREEMENT', '[COLOR_RESEARCH_STORED]Acuerdos de Investigación[ENDCOLOR][NEWLINE]4% de la investigación combinada de ambos jugadores se añade a tu [ICON_RESEARCH] Ciencia al final del acuerdo (8% para países Aliados).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_RA_YES_TT', '[COLOR_RESEARCH_STORED]Proponer Acuerdos de Investigación[ENDCOLOR][NEWLINE]4% de la investigación combinada de ambos jugadores se añade a tur [ICON_RESEARCH] Ciencia al final del acuerdo (8% para países Aliados).[NEWLINE][NEWLINE]Dura {1_num} turnos.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_RA_NO_TT', 'Acuerdo de Investigación activo.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_DEFENSIVE_PACT', '[COLOR_CITY_BROWN]Defensive Pact[ENDCOLOR][NEWLINE]If an outsider declares war on either player, both players declare war on the outsider.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_DEFENSE_YES_TT', '[COLOR_CITY_BROWN]Propose Defensive Pact[ENDCOLOR][NEWLINE]If an outsider declares war on either player, both players declare war on the outsider.[NEWLINE][NEWLINE]Lasts {1_num} turns.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_DEFENSE_NO_TT', 'Defensive Pact active.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_GOLD_STORED', 'Gold Stored', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_GOLD_PROFIT', 'Gold Profit', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_ALLIANCE', '[COLOR_GREEN]Ally[ENDCOLOR][NEWLINE]Doubles income from Mutual Open Borders and Research Agreements, and promotes friendly relations.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_ALLIANCE_YES_TT', '[COLOR_GREEN]Propose Alliance[ENDCOLOR][NEWLINE]Doubles income from Mutual Open Borders and Research Agreements, and promotes friendly relations.[NEWLINE][NEWLINE]Lasts {1_num} turns.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_ALLIANCE_NO_TT', 'We are allied.', '', '');


UPDATE LoadedFile SET Value=1 WHERE Type='GEM_Diplomacy.sql';
