--· ES_ES/Diplomacy.sql
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_DISCUSS_MESSAGE_DEC_FRIENDSHIP_TT', 'Dobla los ingresos procedentes de Acuerdos de Investigación [ICON_RESEARCH] y Apertura de Fronteras Mutua [ICON_GOLD] con este líder. [NEWLINE][NEWLINE]Una alianza promueve la diplomacia amistosa y disuade a los agresores externos. Los aliados pueden solicitar asistencia economica o diplomática, y la falta de apoyo a tu aliado puede molestarlos', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_OPEN_BORDERS_TT', 'Con [COLOR_YIELD_GOLD]acuerdo de apertura de fronteras mutuo[/COLOR], 1% de los Ingresos [ICON_GOLD] combinados de ambos jugadores se añaden a tus ingresos de oro (2% para países Aliados).[NEWLINE][NEWLINE] Permite a las unidades del otro jugador pasar a través de tu territorio.[NEWLINE][NEWLINE](Dura {1_Num} turnos.)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_NOTIFICATION_MINOR_BARB_KILLED', '¡Has acabado con los Bárbaros cerca de {1_CivName:textkey}! Te están muy agradecidos. ¡Has ganado +15 influencia [ICON_INFLUENCE] con ellos!', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_NTFN_RA_FREE_TECH', 'Tu Acuerdo de Investigación con {1_CivName:textkey} ha terminado.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_PEACE_TREATY', 'TRATADO DE PAZ (20 turns)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_PEACE_TREATY_TURNS', 'TRATADO DE PAZ (20 turns)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_ALLOW_EMBASSY_NO_TECH_PLAYER', '[NEWLINE][NEWLINE]No tienes la Tecnología necesaria para establecer una embajada (Comercio).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_ALLOW_EMBASSY_NO_TECH_OTHER_PLAYER', '[NEWLINE][NEWLINE]No tienen la Tecnología necesaria para establecer una embajada (Comercio).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_OPEN_BORDERS_NO_TECH', '[NEWLINE][NEWLINE]Ninguno de los jugadores tiene la tecnología necesaria para completar este acuerdo (Moneda).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_DEF_PACT_NO_TECH', '[NEWLINE][NEWLINE]Ninguno de los jugadores tiene la tecnología necesaria para completar este acuerdo (Gremios).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DIPLO_RESCH_AGREEMENT_NO_TECH', '[NEWLINE][NEWLINE]Ninguno de los jugadores tienn la tecnología necesaria para completar este acuerdo (Filosofía).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_BORDER_AGREEMENT', '[COLOR_YIELD_GOLD]Acuerdo de Apertura de Fronteras Mutuo[ENDCOLOR][NEWLINE]1% de los ingresos combinados de ambos jugadores se añaden a tus ingresos de Oro [ICON_GOLD] (2% para países Aliados).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_BORDERS_YES_TT', '[COLOR_YIELD_GOLD]Proponer Acuerdo Apertura de Fronteras Mutuo[ENDCOLOR][NEWLINE]1% de los ingresos combinados de ambos jugadores se añade a tus ingresos de Oro [ICON_GOLD] (2% si estáis Aliados).[NEWLINE][NEWLINE]Dura {1_num} turnos.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_BORDERS_NO_TT', 'Acuerdo de Apertura de Fronteras Mutuo activa.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_BORDERS_US_TT', 'Nos abren sus fronteras.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_BORDERS_THEM_TT', 'Les abrimos nuestras fronteras.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_RESEARCH_AGREEMENT', '[COLOR_RESEARCH_STORED]Acuerdo de Investigación[ENDCOLOR][NEWLINE]4% de la investigación combinada de ambos jugadores se añade a tu Investigación [ICON_RESEARCH] al final del acuerdo (8% para países Aliados).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_RA_YES_TT', '[COLOR_RESEARCH_STORED]Proponer Acuerdo de Investigación[ENDCOLOR][NEWLINE]4% de la investigación combinada de ambos jugadores se añade a tu Investigación [ICON_RESEARCH] al final del acuerdo (8% para países Aliados).[NEWLINE][NEWLINE]Dura {1_num} turnos.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_RA_NO_TT', 'Acuerdo de Investigación activo.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_DEFENSIVE_PACT', '[COLOR_CITY_BROWN]Acuerdo de Protección[ENDCOLOR][NEWLINE]Si otro país le declara la guerra a cualquiera de los firmantes, ambos jugadores declararán la guerra a ese país.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_DEFENSE_YES_TT', '[COLOR_CITY_BROWN]Proponer Acuerdo de Protección[ENDCOLOR][NEWLINE]Si otro país le declara la guerra a cualquiera de los firmantes, ambos jugadores declararán la guerra a ese país.[NEWLINE][NEWLINE]Dura {1_num} turnos.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_DEFENSE_NO_TT', 'Acuerdo de Protección activo.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_GOLD_STORED', 'Oro Acumulado', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_GOLD_PROFIT', 'Beneficios de Oro', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_ALLIANCE', '[COLOR_GREEN]Aliado[ENDCOLOR][NEWLINE]Dobla los ingresos procedentes de Acuerdos de Apertura de Fronteras Mutuo y de Investigacións, y potencia las relaciones amistosas.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_ALLIANCE_YES_TT', '[COLOR_GREEN]Proponer Alianza[ENDCOLOR][NEWLINE]Dobla los ingresos procedentes de Acuerdos de Apertura de Fronteras Mutuo y de Investigacións, y potencia las relaciones amistosas.[NEWLINE][NEWLINE]Dura {1_num} turnos.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_DEAL_STATUS_ALLIANCE_NO_TT', 'Estamos Aliados.', '', '');


UPDATE LoadedFile SET Value=1 WHERE Type='GEM_Diplomacy.sql';
