--· ES_ES/GreatWorks.sql
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_MISSION_CULTURE_BOMB_DISABLED_COOLDOWN', 'Has creado una Obra de Arte recientemente y y no puedes volver a hacerlo en {1_Num} turnos.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_SPECIALISTSANDGP_CULTUREBOMB_ADV_QUEST', '¿Qué hace la habilidad obra de arte?', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_SPECIALISTSANDGP_CULTUREBOMB_HEADING4_BODY', 'Un Gran Artista puede crear una Obra de Arte en cualquiera de tus ciudades. Las Obras de Arte conceden a la ciudad una gran cantidad de [ICON_CULTURE] Cultura.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_SPECIALISTSANDGP_CULTUREBOMB_HEADING4_TITLE', 'Habilidad Especial: Crear Obra de Arte', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_MISSION_GREAT_WORK', 'Crear Obra de Arte', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_MISSION_GREAT_WORK_HELP', 'Una Obra de Arte concede a la ciudad una gran cantidad de [ICON_CULTURE] Cultura.[NEWLINE][NEWLINE]Crear una Obra de Arte consume al Gran Artista.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_MISSION_GREAT_WORK_ALERT', '{1_greatperson} creada {2_work}. Has ganado {3_culture} [ICON_CULTURE] Cultura en {4_city}!', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_DEFAULT', 'Una obra maestra', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_HOMER', 'La Ilíada', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_THESPIS', 'La primera tragicomedia', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_LING_LUN', 'La escala musical de cinco notas', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_WANG_XIZH', 'El Prefacio a los poemas compuestos en el Pabellón de las Orquídeas', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_VALMIKI', 'El Ramayana', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_VIRGIL', 'La Eneida', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_KALIDAS', 'La leyenda de Sakuntala', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_LI_PO', 'El Borracho en Primavera', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_DU_FU', 'Canciones de los Carros de Guerra', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_JALAL_ALDIN_RUMI', 'Sus Coplas Espirituales', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_DANTE_ALIGHIERI', 'La Divina Comedia', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_YUNUS_EMRE', 'his poems of Sultan Yunu Emre', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_AMIR_KHUSRO', 'La Historia de Cuatro Monjes', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_IBN_MUQLAH', 'La caligrafía thuluth', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_MICHAELANGELO', 'La Estatua de David', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_RAPHAEL', 'La Stanza della Segnatura', '', ''); 
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_WILLIAM_SHAKESPEARE', 'Hamlet', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_MIGUEL_DE_CERVANTES', 'Don Quijote', '', '');  
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_REMBRANDT', 'La Noche de Ronda', '', ''); 
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_JOHANNES_VERMEER', 'La Joven de la Perla', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_JS_BACH', 'Los Conciertos de Brandenburg', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_WOLFGANG_MOZART', 'La Flauta Mágica', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_JOHANN_GOETHE', 'Fausto', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_LUDWIG_VAN_BEETHOVEN', 'Su Quinta Sinfonía', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_VICTOR_HUGO', 'Los Miserables', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_VINCENT_VAN_GOGH', 'Terraza de Café por la Noche', '', ''); 
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_JOHANNES_BRAHMS', 'Las Danzas Húngaras', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_DVORAK', 'Su Sinfonía del Nuevo Mundo', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_MARK_TWAIN', 'Las Aventuras de Tom Sawyer', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_CLAUDE_MONET', 'Impresión, Sol Naciente', '', '');   
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_JOSEPH_CONRAD', 'Victoria', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_FRANK_KAFKA', 'El Proceso', '', '');   
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_LOUIS_ARMSTRONG', 'What a Wonderful World', '', ''); 
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_DUKE_ELLINGTON', 'Toma el Tren ''A'' ', '', '');   
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_PABLO_PICASSO', 'El Guernica', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_MILES_DAVIS', 'Kind of Blue', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_PERSON_TOLSTOY', 'Leo Tolstoy', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_TOLSTOY', 'Guerra y Paz', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_PERSON_DOSTOEVSKY', 'Fyodor Dostoevsky', '', ''); 
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-08'), 'TXT_KEY_GREAT_WORK_DOSTOEVSKY', 'Crimen y Castigo', '', '');


UPDATE LoadedFile SET Value=1 WHERE Type='GEM_GreatWorks.sql';
