/* Traits */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_ART_OF_WAR', 'Los grandes generales ven mas lejos y proporcionan una mayor fuerza extra[NEWLINE] Comienza con un guerrero y un gran general. Obtiene un espía extra.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_ALLOTMENT_SHORT', 'Asignación', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_ALLOTMENT', '+1 [ICON_PRODUCTION] de producción por granja.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_BONUS_AGAINST_TECH', '+10% [ICON_GREAT_PEOPLE] a la creación de grandes personajes por cada alianza y +20% [ICON_STRENGTH] de fuerza contra civilizaciones con mas ciudades.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_CAPITAL_BUILDINGS_CHEAPER', '+25% a la producción [ICON_PRODUCTION] destinada a construir cualquier edificio que ya se encuentre en la capital. [ICON_CAPITAL]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_CITY_STATE_BONUSES', 'Recibe un 25% mas de recomensas de amigos y ciudades-estado aliadas.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_CITY_STATE_FRIENDSHIP', 'La [ICON_INFLUENCE] influencia se degrada a la mitad y se recupera al doble de la velocidad normal. Las ciudades-estado militaristas amigas dan unidades con +20% [ICON_STRENGTH] de fuerza.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS_SHORT', 'Azote de Dios', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS', 'Los campamentos bárbaros se rinden cuando son derrotados. [NEWLINE] Comienza con un arquero a caballo.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_CONVERTS_SEA_BARBARIANS', 'Los barcos de ataque cuerpo a cuerpo capturan los barcos enemigos derrotados. [NEWLINE] Comienza con un guerrero y una Liburna.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_CULTURE_FROM_KILLS', 'Gana [ICON_CULTURE] cultura de matar a las unidades enemigas.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_ENGINEERING_SHORT', 'Valores Prusianos', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_ENGINEERING', '+2 [ICON_PRODUCTION] a la producción de los científicos, y +2 [ICON_RESEARCH] de ciencia para los ingenieros.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_ENHANCED_CULTURE', '+3 [ICON_CULTURE] de cultura por turno de ciudades antes de descubrir las maquinas de vapor.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_ENHANCED_GOLDEN_AGES', '+50% [ICON_CULTURE] de cultura y +1[ICON_MOVES] de movimiento durante las[ICON_GOLDEN_AGE] edades de Oro.[NEWLINE] Empieza con un inmortal.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_FAITH_FROM_NATURE', '+1 [ICON_PEACE] de fe por los bosques y la selva no mejoradas y dobla el rendimiento de las maravillas naturales. [NEWLINE] Empieza con un guerrero picto.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_FASTER_RANGED_SHORT', 'Usurpador', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_FASTER_RANGED', 'Las unidades [ICON_RANGE_STRENGTH] de ataque a distancia se mueven más rápido, y las unidades de reconocimiento ven más lejos. [NEWLINE] Empieza con un arquero.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_FIGHT_WELL_DAMAGED', 'Las unidades heridas luchan como si tuvieran toda su vida.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_GREAT_ANDEAN_ROAD', 'Las unidades se mueven más rápido en las colinas. Mantenimiento gratuito de carreteras y vías férreas en las colinas, y a mitad de costo en el resto de casillas.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_HARAPPAN_ENGINEERING_SHORT', 'Ingeniería Harappa', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_HARAPPAN_ENGINEERING', '+1 [ICON_MOVES] al movimiento de las unidades civiles. [NEWLINE] Comienza con un trabajador.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_IGNORE_TERRAIN_IN_FOREST', 'Movimiento mas rápido en bosques y selva, que cuentan como caminos en territorio amigo. [NEWLINE] Comienza con un guerrero Mohicano.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_INGENIOUS', '+25% a la creación de grandes científicos y recibe uno gratis al conseguir la escritura.[NEWLINE] Empieza con un saetero.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_LAND_TRADE_GOLD_SHORT', 'Caravanas del desierto', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_LAND_TRADE_GOLD', 'Cada recurso de lujo aumenta los ingresos [ICON_GOLD] de oro en un 5%, y las unidades se mueven más rápido en terreno desértico.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_LONG_COUNT', 'Después de investigar Teología, recibirán un gran personaje en el final de la larga cuenta del calendario maya (cada 394 años). [NEWLINE] Comienza con un Lanzadardos.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_WONDER_BUILDER', '+20% [ICON_PRODUCTION] a la producción para la construcción de maravillas.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_OCEAN_MOVEMENT', '+30 [ICON_WAR] a la experiencia de las unidades navales.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_EXTRA_BELIEF', 'Elije una creencia más de lo normal cuando fundes una religión.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_PHOENICIAN_HERITAGE', 'Los trabajadores pueden cruzar el agua, y cada puerto recibe gratis un faro.[NEWLINE] Las unidades pueden cruzar montañas. Empieza con un Trirreme y un guerrero. ', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_POPULATION_GROWTH', 'Los edificios dedicados a la alimentación añaden 1 [ICON_CITIZEN] a la población una vez construidos. [NEWLINE] Comienza con un trabajador.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_RAZE_AND_HORSES', 'Los campamentos bárbaros que se rinden al ser derrotados proporcionan el doble [ICON_GOLD] de oro. [NEWLINE] Comienza con un arquero a caballo.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_RIVER_EXPANSION_SHORT', 'Sueño Americano', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_RIVER_EXPANSION', '+1 [ICON_HAPPINESS_1] de felicidad por ciudad, las unidades de tierra ven más lejos, los civiles se mueven más rápido. [NEWLINE] Comienza con un batidor.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_SCHOLARS_JADE_HALL_SHORT', 'Dinastía Joseon', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_SCHOLARS_JADE_HALL', '+2 [ICON_RESEARCH] de ciencia por granjas.[NEWLINE] Empieza con un trabajador.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_SEVEN_CITIES', 'Rendimiento doble por cada maravilla natural, gana 100 [ICON_GOLD] de oro al descubrirlas.[NEWLINE] Comienza con un batidor, y recibe una carabela al descubrir la brújula.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_STRATEGIC_RICHES', '+1 [ICON_PRODUCTION] a la producción por recursos estratégico, ademas proporcionan el doble de recursos.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_TERROR', '+1 [ICON_MOVES] de movimiento para unidades montadas y de exploracion. +25% extra de rendimiento en la captura de ciudades-estado. Empieza con un Batidor.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_VIKING_FURY_SHORT', 'Drakkar', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TRAIT_VIKING_FURY', 'Las unidades embarcan más rápido y son más fuertes por el agua, y las unidades de cuerpo a cuerpo saquean más rápido.', '', '');
/* Units */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_UNIT_HELP_MUSLIM_CAVALRY', 'Unidad exclusiva Songhai montada.La caballería se inicia con la promoción Asedio, a diferencia del caballero al que sustituye.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_UNIT_HELP_SAMURAI', 'Potente soldado medieval exclusivo japonés. El samurai puede atacar dos veces por turno, y son más fuertes que el soldado con espada larga al que sustituyen.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_CIV5_BABYLON_BOWMAN_HELP', 'Unidad exclusiva babilónica a distancia. El Saetero es más fuerte que el arquero al que sustituye, y se mueve mas rápido por desiertos.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_CIV5_DENMARK_BERSERKER_HELP', 'Soldado de la época medieval exclusivo de Dinamarca. El Berserk comienza con la promoción de carga, a diferencia del  soldado con espada larga al que sustituye.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_UNIT_HELP_PANZER', 'Unidad con gran movilidad exclusiva de Alemania. El Panzer tiene mayor fuerza, velocidad, y la visibilidad que el Tanque que reemplaza.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_UNIT_HELP_JAGUAR', 'Soldado de comienzos de partida exclusivo para los aztecas. El Jaguar se cura cuando  mata a un enemigo, y combate con mayor eficacia en la selva que el guerrero al que sustituye.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_UNIT_HELP_MINUTEMAN', 'Unidad de exploración del renacimiento exclusiva para los americanos. Es más fuerte que el escaramuzador al que sustituye, ve más lejos, y se mueve más rápido en terrenos difíciles....', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_UNIT_HELP_MUSKETEER', 'Una primeras unidades de pólvora del juego, exclusivos los franceses. Los mosqueteros tienen una bonificación de combate fuera de territorio amigo, a diferencia del Mosquete al que sustituye.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_UNIT_IROQUOIAN_MOHAWKWARRIOR_STRATEGY', 'Unidad exclusiva de los iroqueses. El guerrero Mohicano lucha más fuerte en el bosque y la selva que el soldado con espada al que sustituye.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_UNIT_OTTOMAN_JANISSARY_STRATEGY', 'Soldado exclusivo de los otomanos. El jenízaro es mucho más fuerte en ataque y se cura después de matar, a diferencia del Mosquete al que sustituye.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_PROMOTION_MEDIC_GENERAL_HELP', 'Las unidades en una casilla[COLOR_POSITIVE_TEXT] curan 4 puntos adicionales [ENDCOLOR] por turno.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_CIV5_MONGOLIA_KESHIK_HELP', 'La unidad exclusiva de Mongolia en sustitución del caballero se mueve más rápido, ataca a distancia, y no comparte las vulnerabilidades del Caballero contra ciudades o piqueros. El Keshik también gana experiencia con mayor rapidez.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_UNIT_HELP_FOREIGN_LEGION', 'Soldado básico de la era industrial exclusivo de los franceses. La legión extranjera cuesta mucho menos que la infantería I guerra a la que sustituye.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_UNIT_HELP_ROMAN_LEGION', 'Potente soldado romano de la época clásica con un bono contra las Ciudades. La Legión tiene mayor fuerza que el soldado con espada al que sustituye, defensa adicional contra ataques a distancia, y puede construir carreteras al doble de la velocidad de los Trabajadores.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_UNIT_HELP_INDIAN_WAR_ELEPHANT', 'Potente unidad montada exclusiva de la India. A diferencia del jinete al que sustituye, el elefante de guerra ataca a distancia, no requiere de caballos, y no tiene la vulnerabilidad a los lanceros.', '', '');
/* Misc */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILD_MOAI_HELP', '+3 [ICON_CULTURE] de cultura. [NEWLINE] +1 [ICON_CULTURE] de Cultura por Moai adyacente. [NEWLINE] [ICON_LOCKED] Tiene que estar al lado de la costa.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_CIV5_IMPROVEMENTS_MOAI_HELP', '+3 [ICON_CULTURE] de cultura. [NEWLINE] +1 [ICON_CULTURE] de Cultura por Moai adyacente. [NEWLINE] [ICON_LOCKED] Tiene que estar al lado de la costa.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_POLYNESIAN_SCENARIO_BUILD_MOAI_HELP', '+3 [ICON_CULTURE] de cultura. [NEWLINE] +1 [ICON_CULTURE] de Ccultura por Moai adyacente. [NEWLINE] [ICON_LOCKED] Tiene que estar al lado de la costa.', '', '');
/*  Jelling Stones */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_JELLING_STONES', 'Piedras de Jelling', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_JELLING_STONES_PEDIA', 'Las rocas son enormes piedras rúnicas en Jelling talladas en el siglo 10,se encuentra en la localidad de Jelling en Dinamarca. La más antigua de las dos piedras de Jelling fue creada por el rey Gorm en memoria de su esposa Thyra. La mayor de las dos piedras se construyo por Harald Bluetooth, hijo del rey Gorm. Harald construyó la segunda piedra en memoria de sus padres, en celebración de la conquista de Dinamarca y Noruega, y la conversión de los daneses al cristianismo. Las inscripciones rúnicas en estas piedras son muy conocidas en Dinamarca.', '', '');
/*  Jade Hall */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_JADE_HALL', 'Salón de Jade', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_JADE_HALL_PEDIA', 'El rey Sejong supervisó el desarrollo de el Chiphyonjon, el Salón Jade de los Académicos, donde investigadores profesionales que ayudaron a evolucionar en cuestiones sociales, políticas y de investigación trabajando para el rey y el gobierno. El Salón Jade es considerado un "grupo de reflexión" por los gobiernos en la actualidad.', '', '');
/*  Indus Sanitation */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_INDUS_SANITATION', 'Sanidad del Indo', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_INDUS_SANITATION_PEDIA', 'La civilización Harappa del valle del río Indo diseño el primer sistema de saneamiento urbano conocido alrededor de 2600 aC. Las Viviendas individuales o grupos de hogares obtenian agua de pozos. El agua residual se dirigia desde las habitaciones asignadas a bañarse a largas cubiertas de drenaje de las calles principales. Los enormes muros de las ciudades de Harappa se especula que servían para protegerse de las inundaciones. Estos sistemas de ingeniería hidráulica Harappa eran más eficientes que los de muchas zonas de Pakistán y la India de hoy, logrando grandes ciudades urbanas a pesar del relativamente bajo desarrollo de la agricultura de la época.', '', '');
/*  Pioneer Fort */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_PIONEER_FORT', 'Fuerte de pioneros', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_PIONEER_FORT_PEDIA', 'Fuerte es toda obra pequeña de fortificación, permanente o pasajera, que defiende un paso o constituye parte de un sistema. Según su traza, objeto, disposición o capacidad, el fuerte es abaluartado, aislado, abierto, avanzado, cerrado, de estrella, destacado, independiente, etc. Muy utilizados por los colonos americanos.', '', '');
/*  Pioneer */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_UNIT_AMERICAN_PIONEER', 'Pionero', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_UNIT_AMERICAN_PIONEER_HELP', 'Funda nuevas ciudades para expandir el imperio. [NEWLINE] [NEWLINE] [ICON_FOOD] El crecimiento de la ciudad se detiene mientras la unidad está en construcción. [NEWLINE]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_UNIT_AMERICAN_PIONEER_STRATEGY', 'El Pionero es una unidad exclusiva estadounidense. Se mueve más rápido que el colono al que sustituye. [NEWLINE] [NEWLINE] Utilice esta unidad para construir nuevas ciudades. No puede defenderse, por lo que se recomienda acompañar con una unidad de combate.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_UNIT_AMERICAN_PIONEER_PEDIA', 'Pionero americano es como se llama a las personas en la historia de EE.UU. que emigraron al oeste de la costa del Atlántico para establecerse y desarrollar nuevas áreas. El término se refiere especialmente a los que iban a establecerse en un nuevo territorio desde la sociedad europea o estadounidense, a pesar de que el territorio podría estar siendo habitado o utilizado por los pueblos indígenas. [NEWLINE] [NEWLINE] El concepto pionero y su carácter distintivo es muy anterior a la migración a las partes de los Estados Unidos que ahora se llaman "desarrolladas", como en muchos lugares que ahora se consideran como salvajes se establecieron también los pioneros de la costa. Por ejemplo, Daniel Boone, una figura clave en la historia de los pioneros americanos, se instaló en Kentucky, cuando esa era "tierra oscura y sangrienta" todavía sin desarrollar. [NEWLINE] [NEWLINE] Una novedad importante en el asentamiento occidental fue el acto de la granja, que proporcionó legislación formal que regula el proceso de liquidación.', '', '');
/* Steam Mill */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_STEAM_MILL', 'Molino de vapor', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_STEAM_MILL_PEDIA', 'Una transición se inició a base de factorías basadas en maquinas en la economía de Gran Bretaña de la década de 1700, anteriormente eran dependientes de la mano de obra y los animales de tiro. Estos precursores de la Revolución Industrial comenzaron con la mecanización de las industrias textiles. La expansión del comercio fue posible gracias a la introducción de canales, caminos mejorados, y los ferrocarriles. La gran utilización de ruedas de agua y la introducción de una máquina de vapor como motor propicio un aumento espectacular en la capacidad de producción. El desarrollo de todas las herramientas mecanizadas de metal a principios de 1800 facilitó la construcción de máquinas de producción cada vez más refinadas para la fabricación en una amplia variedad de industrias.', '', '');
/* Dojo */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_DOJO', 'Dojo', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_DOJO_PEDIA', 'Un dojo  japonés ("lugar del camino") es un lugar de reunión para llevar a cabo la formación, exámenes, y otros encuentros relacionados con las artes del "despertar".Los Dojos inicialmente se adjuntan a los templos. En Japón, cualquier centro de entrenamiento físico, incluidas las escuelas de lucha libre profesional, puede ser llamado dojo por sus raíces cercanas artes marciales.', '', '');
/* Shrine */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_JAPANESE_SHRINE', 'Santuario Shinto', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_JAPANESE_SHRINE_PEDIA', 'En Japón, los santuarios sintoístas conviven con templos budistas, y son los sitios religiosos más numerosos, famosos e importantes en Japón. Un santuario sintoísta es una estructura u objeto cuya finalidad principal es la casa de uno o más Shinto kami(espíritus, fuerzas de la naturaleza o esencias). Kami pueden residir en cualquier cosa natural o creada por el hombre, desde el monte Fuji a una pequeña joya. Como tales, estos santuarios son comunes y varían ampliamente en su alcance. El propio Santuario puede ser un edificio grande o pequeño objeto, a lo largo de una carretera, o incluso podría ser llevado por la gente. [NEWLINE] [NEWLINE] Al igual que los templos budistas, los santuarios sintoístas no son ante todo un lugar de culto. Los edificios más importantes del santuario se utilizan para la custodia de los objetos sagrados. Hay edificios especializados para ciertos ritos, pero éstos suelen estar abiertos únicamente a un número limitado de participantes. Las reuniones religiosas de masas al estilo de las iglesias cristianas no tienen lugar con regularidad y no se encuentran dentro de una capilla. Si muchas personas están involucradas en una ceremonia, esta asumirá un carácter festivo y se llevará a cabo al aire libre.', '', '');
/* Folkskola */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_FOLKSKOLA', 'Folkskola', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_FOLKSKOLA_PEDIA', 'En 1842, el Parlamento sueco introdujo una escuela primaria de cuatro años para los niños en Suecia ,es un "Colegio público" (escuela del pueblo). Este fue uno de los primeros sistemas de escuelas públicas en el mundo. [NEWLINE] [NEWLINE] Los niños suecos están obligados a asistir a la escuela primaria, la escuela obligatoria, desde los 7 a 16, donde la educación primaria es una combinación de la enseñanza primaria y secundaria. Después de la escuela primaria, muchos suecos pueden asistir a la secundaria,o bachillerato, pudiendo elegir entre un programa universitario preparatorio o un programa vocacional. Los estudiantes que elijan un programa vocacional normalmente terminan su educación después de la secundaria, mientras que los estudiantes que completan un programa universitario preparatorio generalmente se matriculan en la educación superior, en un colegio universitario o universidad. Los estudiantes que completan un programa profesional se pueden inscribir en la educación superior también, pero deben realizar cursos adicionales antes de ser admitidos.', '', '');
/* Basilica */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_BASILICA', 'Basilica', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILDING_BASILICA_PEDIA', 'La palabra Latina "Basilica" (derivado del griego Stoa, la cámara del tribunal del rey) era originalmente designada para describir un edificio público romano situado en el foro de las ciudades. Por extensión, se aplica a los edificios cristianos de la misma forma. [NEWLINE] [NEWLINE] En el siglo cuarto, una vez que las autoridades imperiales habían despenalizado el cristianismo con el edicto de Milán de 313 D.C, los cristianos estaban dispuestos a construir edificios más grandes y más atractivos para la adoración, en lugar de los furtivos lugares de reunión que habían estado utilizando hasta ese momento. Las tradicionales fórmulas arquitectónicas de los templos eran inadecuados debido a la asociación con creencias no cristianas. Las antiguas ceremonias del templo se producian al aire libre bajo el cielo abierto ante los ojos de los dioses, con el templo como telón de fondo. El modelo Constantino que quería conmemorarse por su piedad imperial, fue de una arquitectura de (previamente secular)basada en basílicas, y en la celebración de ceremonias en interiores.', '', '');
/* Cothon */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_BUILDING_COTHON', 'Cothon', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-12'), 'TXT_KEY_BUILDING_COTHON_PEDIA', 'Un cothon (en griego: "vasija para beber") es un puerto artificial, protegido interior como el de Cartago en las Guerras Púnicas del 200 A.C. [NEWLINE] Los Cothons se encuentran generalmente en el mundo fenicio. Los ejemplos incluyen Motya (Sicilia) desde el siglo 6 A.C, que realizaba un proposito aun incierto, (Mide 35 metros x 51 metros), aunque se ha sugerido que este cothon incluso podría haber sido susceptible a cierres y drenajes, hasta formar un dique seco. Mahdia (Túnez) desde el siglo séptimo antes de Cristo, (que mide 72 metros x 56 metros) y uno de Kition en Chipre.', '', '');
