--· ES_ES/Research.sql
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-04-02'), 'TXT_KEY_TECH_TRAINING', 'Entrenamiento', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TECH_TRAINING_PEDIA', 'El entrenamiento militar es un proceso para establecer y mejorar las capacidades del personal militar. La educación militar puede ser voluntaria u obligatoria. [NEWLINE] El entrenamiento de los reclutas pretende enseñar la información básica y la formación en las técnicas necesarias para ser un miembro del servicio efectivo. Para lograr esto, los miembros del servicio están sometidos a pruebas físicas, técnicas y psicológicas. [NEWLINE] Después de terminar el entrenamiento básico, muchos miembros del servicio se someten a un entrenamiento mas avanzado acorde a sus especialidades elegidas o asignadas. En el entrenamiento avanzado, a menudo se enseña a usar tecnología y equipos militares sofisticados.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TECH_TRAINING_QUOTE', 'La conscripción es necesaria, pero no necesariamente el reclutamiento.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TECH_TRADE_TITLE', 'Comercio', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TECH_TRADE_DESC', 'El comercio se originó con el comienzo de la comunicación entre poblaciones en tiempos prehistóricos. Estimuló la curiosidad común, el ingenio y el aprendizaje de idiomas. Gracias a ese comercio, y la especialización que engendró, se consiguió la aceleración del crecimiento de la conciencia humana y el triunfo de los seres humanos sobre la especie neandertal. [NEWLINE] [NEWLINE] Hay evidencia del intercambio de obsidiana y sílex durante la Edad de Piedra. Egipto negociaba para conseguir materiales útiles para la creación de joyas desde el año 3000 antes de Cristo. Las rutas comerciales de largo alcance aparecieron por primera vez con los sumerios, en Mesopotamia. Comerciaban con la civilización Harappa del valle del Indo. Los fenicios - notables comerciantes marítimos - viajaron a través del Mar Mediterráneo, y tan al norte que llegaron incluso a Gran Bretaña buscando las fuentes de estaño para fabricar bronce. Establecieron colonias comerciales que los griegos llamaron emporios. [NEWLINE] [NEWLINE] El comercio continuó impulsando la tendencia humana a explorar mucho después de la desaparición de los antiguos imperios marítimos mediterráneos. El comercio a larga distancia se extendió aún más lejos con la enorme flota de Sheng He, que llegó a la India, Arabia y África Oriental antes de que Colón cruzara el océano.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TECH_TRADE_QUOTE', '[NEWLINE][TAB][TAB]"Actualmente no existe razón para negar o la presencia o el impacto de la economía en los albores pre-históricos de la humanidad"[NEWLINE][TAB][TAB] - Jason Shogren[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_DIPLO_NEED_WRITING_TT', '[NEWLINE] [NEWLINE] Ninguno de los jugadores tiene todavía la tecnología necesaria para cambiar este objeto (Comercio).', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-04-02'), 'TXT_KEY_TECH_CARVEL_HULLS', 'Armazón de Carabela', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TECH_CARVEL_HULLS_PEDIA', 'El diseño de la carabela fue uno de los acontecimientos críticos que permitió la dominación de las potencias navales de Europa occidental desde 1400 hasta el presente. Los tablones de madera en los cascarones de las Carabelas se alineaban el uno con el otro, borde con borde, en lugar del antiguo diseño de superposición de tablones en los casos de diseño trincado. Este diseño del casco más fuerte permite la creación de barcos mucho más grandes y con enormes velas.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TECH_CARVEL_HULLS_QUOTE', '[NEWLINE][TAB][TAB]"Un barco está seguro en el puerto, pero eso no es para lo que está hecho."[NEWLINE][TAB][TAB] - William Shedd.[NEWLINE]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-04-02'), 'TXT_KEY_TECH_MASS_MEDIA_TITLE', 'Medios de comunicación', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TECH_MASS_MEDIA_DESC', 'El término "medios de comunicación" fue acuñado en la década de 1920 con la llegada de la radio, pero la idea de los medios de comunicación para el consumo del gran público ha estado presente desde la época de los dramas y obras de teatro de la Antigüedad. Los medios de comunicación se ha visto directamente impulsados por la tecnología, con mayores avances en las técnicas editoriales y de comunicación, que intentan abarcar al público más amplio posible al que tienen alcance. [NEWLINE] [NEWLINE] Originalmente el termino sólo se aplica a los dispositivos de comunicación como la radio, periódicos y revistas, pero ahora abarca televisión, películas, música, libros de bolsillo, los videojuegos e Internet. Con la llegada de este tipo de medios de comunicación que abarcan todo el mundo se ha planteado la posibilidad de llegar a las masas como nunca antes, y no siempre en el buen sentido. El intento de controlar y manipular a la población con la información, ya sea vilmente a través de la propaganda o con opiniones personales más inocentes es un hecho, se está convirtiendo en un gran problema para algunos gobiernos y organizaciones. Las técnicas invasivas de publicidad son también un subproducto de los medios de comunicación, para gran disgusto de los consumidores en todas partes. Por otra parte son también muy útiles y es cada vez más fácil para una persona común publicar sus ideas y obras de arte, consiguiendo ser escuchado en la salida torrencial de información ahora disponible aunque encontrar información realmente puede ser como buscar la aguja en un pajar.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TECH_MASS_MEDIA_QUOTE', '[NEWLINE] [TAB] [TAB] "La velocidad de las comunicaciones es algo maravilloso de ver, pero también es cierto que la velocidad puede multiplicar la difusión de la información que sabemos que no es verdad.". [NEWLINE] [TAB] [TAB] - Edward R. Murrow. [NEWLINE] [TAB] [TAB] [TAB]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-04-02'), 'TXT_KEY_TECH_MASS_PRODUCTION_TITLE', 'Producción en masa', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TECH_MASS_PRODUCTION_DESC', 'La producción en masa moderna es la construcción de grandes cantidades de productos estandarizados en las líneas de montaje. Las Herramientas industriales para grandes maquinas, las piezas intercambiables, los científicos, administrativos y la energía eléctrica son los ingredientes mas importantes para la producción en masa. [NEWLINE] [NEWLINE] La producción en masa se ​​popularizó en la década de 1910 y 1920 por Henry Ford de Ford Motor Company, que introdujo los motores eléctricos -La muy conocida técnica de la cadena de producción o secuencial.- Ford también ha comprado, diseñado o construido máquinas, herramientas  y accesorios para agilizar la producción. Todas estas "máquinas herramienta" se organizaron sistemáticamente en el flujo de producción. La gestión de Ford llevaba a cabo estudios de tiempo y experimentos para mecanizar sus procesos de fabricación, centrándose en reducir al mínimo los movimientos de los trabajadores.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TECH_MASS_PRODUCTION_QUOTE', '[NEWLINE][TAB][TAB]"Una regla para un empresario es: fabrica los mejores bienes posibles al menor precio posible, pagando los mayores sueldos posibles"[NEWLINE][TAB][TAB] - Henry Ford.[NEWLINE][TAB]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-04-02'), 'TXT_KEY_TECH_ION_PROPULSION_TITLE', 'Propulsión Iónica', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TECH_ION_PROPULSION_DESC', 'La propulsión que eligen los escritores de ciencia ficción se ha convertido en la propulsión de eligen los científicos e ingenieros de la NASA. El uso eficiente del sistema sistema de propulsión iónica de combustible y energía eléctrica permiten las actuales naves espaciales viajar más lejos, más rápido y más barato que con cualquier otra tecnología de propulsión actualmente disponible. Los Propulsores de iones se utilizan actualmente para las estaciones de mantenimiento de los satélites de comunicación y para la propulsión principal de sondas del espacio profundo. Los propulsores de iones expulsan iones para crear el impulso y pueden proporcionar mayores velocidades para naves espaciales mejores que cualquier otro cohete disponible actualmente. [NEWLINE] Un ión es simplemente un átomo o molécula que se carga eléctricamente. En un motor iónico, los iones son acelerados por las fuerzas electrostáticas. Los campos eléctricos utilizados para la aceleración son generados por electrodos colocados en el extremo bajo el motor de propulsión [NEWLINE]Los motores modernos de iones usan gases inertes para el propulsor. La mayoría de los propulsores utilizan xenón, que es químicamente inerte, incoloro, inodoro e insípido. También se disparan electrones al haz de iones que sale de las rejillas como iones cargados positivamente que dejan el propulsor. Esto mantiene a la nave espacial y el haz del propulsor electricamente neutrales. ', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_TECH_ION_PROPULSION_QUOTE', '[NEWLINE][TAB][TAB]"Las civilizaciones se vuelven espaciales..o extintas"[NEWLINE][TAB][TAB] - Carl Sagan.[NEWLINE][TAB]', '', '');

UPDATE LoadedFile SET Value=1 WHERE Type='GEM_Research.sql';
