INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_RESOURCE_MOVIES', 'Películas.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_RESOURCE_MOVIES_PEDIA', 'Una película, filme o proyección cinematográfica, es como se llama a una secuencia de imágenes fotográficas tomadas con una cámara, que reproducidas mediante un proyector en una pantalla, crean la ilusión de imágenes en movimiento. Se crea captando escenas reales con una cámara de cine, reproduciendo secuencias de dibujos, de  modelos y maquetas en miniatura, por medio de CGIs y animación por ordenador, o por una combinación de todas o alguna de estas técnicas y efectos visuales. El proceso de hacer cine es un arte y también constituye una gran industria.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_RESOURCE_TYRIAN_PURPLE', 'Esto mejorará la defensa [ICON_STRENGTH] de cualquier unidad militar destinada en esta casilla, y quitara 20 de vida a los enemigos adyacentes.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_RESOURCE_TYRIAN_PURPLE_PEDIA', '[COLOR_NEGATIVE_TEXT] Cuesta [ENDCOLOR] 3 de oro por [ICON_GOLD] turno de mantenimiento. [NEWLINE] [NEWLINE] +50% de fuerza defensiva [ICON_STRENGTH] para cualquier unidad estacionada en la casilla, y quita 20 de vida a los enemigos adyacentes.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILD_FORT_REC', '[COLOR_NEGATIVE_TEXT] Cuesta [ENDCOLOR] 3 de oro [ICON_GOLD] por turno de mantenimiento. [NEWLINE] [NEWLINE] Una fortaleza es una mejora especial que aumenta la bonificación defensiva de una casilla, y quita 20 de vida a los enemigos adyacentes. Sin embargo, estos efectos no se aplican en el territorio enemigo.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILD_FORT_HELP', 'Proporciona 100 de oro [ICON_GOLD] al primer jugador que lo descubra.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_CIV5_IMPROVEMENTS_FORT_TEXT', 'Islas.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_CIV5_FEATURES_EL_DORADO_HELP', 'Islas.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_FEATURE_ATOLL', 'Una isla es cualquier territorio sub-continental de tierra que esta rodeado por agua. Las islas muy pequeñas pueden ser llamadas islotes, cayos  o isleta.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_CIV5_FEATURES_ATOLL', 'Islas.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_CIV5_FEATURES_ATOLL_TEXT', 'Una isla es cualquier territorio sub-continental de tierra que esta rodeado por agua. Las islas muy pequeñas pueden ser llamadas islotes, cayos  o isleta.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_SPECIALISTSANDGP_CITADEL_HEADING4_BODY', '{TXT_KEY_BUILD_CITADEL_HELP}', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-13'), 'TXT_KEY_BUILD_CITADEL_HELP', '+100% [COLOR_POSITIVE_TEXT] de defensa [ICON_STRENGTH][ENCOLOR] en esta casilla. [NEWLINE] Quita 30 [COLOR_POSITIVE_TEXT] de vida [ICON_RANGED_STRENGTH] [ENCOLOR] por turno a los enemigos adyacentes [NEWLINE] Expande las fronteras [ICON_CULTURE] a las casillas de alrededor. [NEWLINE] Requiere estar en territorio amigo [ICON_LOCKED].', '', '');

UPDATE LoadedFile SET Value=1 WHERE Type='GEM_Terrain.sql';
