-- 

INSERT INTO Building_ResourceYieldChanges (BuildingType, ResourceType, YieldType, Yield)
SELECT 'BUILDING_ENGLISH_STEAM_MILL', res.Type, yield.Type, 1
FROM Resources res, Yields yield
WHERE res.Happiness <> 0 AND yield.Type IN ('YIELD_GOLD', 'YIELD_PRODUCTION');

UPDATE Units SET GoodyHutUpgradeUnitClass = NULL WHERE Type IN (
	'UNIT_PERSIAN_IMMORTAL'			,
	'UNIT_HUN_HORSE_ARCHER'			,
	'UNIT_IROQUOIAN_MOHAWKWARRIOR'	,
	'UNIT_BABYLONIAN_BOWMAN'		,
	'UNIT_MAYAN_ATLATLIST'			
);

INSERT INTO Trait_FreeUnitAtTech
		(TraitType, TechType, UnitClassType)
SELECT	'TRAIT_INGENIOUS', 'TECH_WRITING', 'UNITCLASS_SCIENTIST'
WHERE EXISTS (SELECT * FROM Traits WHERE Type='TRAIT_INGENIOUS');

UPDATE Leaders SET AIBonus = 1
WHERE Type IN (
	'LEADER_ASKIA',
	'LEADER_AUGUSTUS',
	'LEADER_ELIZABETH',
	'LEADER_GENGHIS_KHAN',
	'LEADER_HARALD',
	'LEADER_ISABELLA',
	'LEADER_ODA_NOBUNAGA'
);

--
-- Unique Units
--


UPDATE Units SET	   Cost   = ROUND(1.00 * (SELECT Cost   FROM Units WHERE Type = 'UNIT_SKIRMISHER'), 0)
					   WHERE Type IN ('UNIT_AMERICAN_MINUTEMAN');
UPDATE Units SET	   Combat = ROUND(1.15 * (SELECT Combat FROM Units WHERE Type = 'UNIT_SKIRMISHER'), 0)
					   WHERE Type IN ('UNIT_AMERICAN_MINUTEMAN');

UPDATE Units SET	   Combat = ROUND(1.25 * (SELECT Combat FROM Units WHERE Type = 'UNIT_WARRIOR'), 0)
					   WHERE Type IN ('UNIT_AZTEC_JAGUAR');

UPDATE Units SET	   Combat = ROUND(1.15 * (SELECT Combat FROM Units WHERE Type = 'UNIT_CROSSBOWMAN'), 0)
					   WHERE Type IN ('UNIT_CHINESE_CHUKONU');
UPDATE Units SET RangedCombat = ROUND(1.15 * (SELECT RangedCombat FROM Units WHERE Type = 'UNIT_CROSSBOWMAN'), 0)
					   WHERE Type IN ('UNIT_CHINESE_CHUKONU');

UPDATE Units SET	   Combat = ROUND(1.15 * (SELECT Combat FROM Units WHERE Type = 'UNIT_LONGSWORDSMAN'), 0)
					   WHERE Type IN ('UNIT_DANISH_BERSERKER');

UPDATE Units SET	   Combat = ROUND(1.00 * (SELECT Combat FROM Units WHERE Type = 'UNIT_CHARIOT_ARCHER'), 0)
					   WHERE Type IN ('UNIT_EGYPTIAN_WARCHARIOT');
UPDATE Units SET RangedCombat = ROUND(1.40 * (SELECT RangedCombat FROM Units WHERE Type = 'UNIT_CHARIOT_ARCHER'), 0)
					   WHERE Type IN ('UNIT_EGYPTIAN_WARCHARIOT');

UPDATE Units SET	   Combat = ROUND(0.80 * (SELECT Combat FROM Units WHERE Type = 'UNIT_CROSSBOWMAN'), 0)
					   WHERE Type IN ('UNIT_ENGLISH_LONGBOWMAN');

UPDATE Units SET	   Combat = ROUND(1.00 * (SELECT Combat FROM Units WHERE Type = 'UNIT_MUSKETMAN'), 0)
					   WHERE Type IN ('UNIT_FRENCH_MUSKETEER');

UPDATE Units SET	   Cost   = ROUND(0.75 * (SELECT Cost   FROM Units WHERE Type = 'UNIT_INFANTRY'), 0)
					   WHERE Type IN ('UNIT_FRENCH_FOREIGNLEGION');

UPDATE Units SET	   Cost   = ROUND(0.80 * (SELECT Cost   FROM Units WHERE Type = 'UNIT_PIKEMAN'), 0)
					   WHERE Type IN ('UNIT_GERMAN_LANDSKNECHT');

UPDATE Units SET	   Cost   = ROUND(1.00 * (SELECT Cost   FROM Units WHERE Type = 'UNIT_MODERN_ARMOR'), 0)
					   WHERE Type IN ('UNIT_GERMAN_PANZER');

UPDATE Units SET	   Combat = ROUND(1.10 * (SELECT Combat FROM Units WHERE Type = 'UNIT_SPEARMAN'), 0)
					   WHERE Type IN ('UNIT_GREEK_HOPLITE');
					   
UPDATE Units SET	   Cost   = ROUND(1.00 * (SELECT Cost   FROM Units WHERE Type = 'UNIT_HORSEMAN'), 0)
					   WHERE Type IN ('UNIT_INDIAN_WARELEPHANT');
UPDATE Units SET	   Combat = ROUND(0.65 * (SELECT Combat FROM Units WHERE Type = 'UNIT_HORSEMAN'), 0)
					   WHERE Type IN ('UNIT_INDIAN_WARELEPHANT');
UPDATE Units SET RangedCombat = ROUND(0.85 * (SELECT Combat FROM Units WHERE Type = 'UNIT_HORSEMAN'), 0)
					   WHERE Type IN ('UNIT_INDIAN_WARELEPHANT');

UPDATE Units SET	   Combat = ROUND(1.00 * (SELECT Combat FROM Units WHERE Type = 'UNIT_RIFLEMAN'), 0)
					   WHERE Type IN ('UNIT_JAPANESE_SAMURAI');

UPDATE Units SET	   Combat = ROUND(0.90 * (SELECT Combat FROM Units WHERE Type = 'UNIT_CANNON'), 0)
					   WHERE Type IN ('UNIT_KOREAN_HWACHA');
UPDATE Units SET RangedCombat = ROUND(0.90 * (SELECT RangedCombat FROM Units WHERE Type = 'UNIT_CANNON'), 0)
					   WHERE Type IN ('UNIT_KOREAN_HWACHA');

UPDATE Units SET	   Combat = ROUND(1.15 * (SELECT Combat FROM Units WHERE Type = 'UNIT_SPEARMAN'), 0)
					   WHERE Type IN ('UNIT_PERSIAN_IMMORTAL');
					   
UPDATE Units SET	   Combat = ROUND(1.25 * (SELECT Combat FROM Units WHERE Type = 'UNIT_WARRIOR'), 0)
					   WHERE Type IN ('UNIT_POLYNESIAN_MAORI_WARRIOR');

UPDATE Units SET	   Cost   = ROUND(1.15 * (SELECT Cost   FROM Units WHERE Type = 'UNIT_SWORDSMAN'), 0)
					   WHERE Type IN ('UNIT_ROMAN_LEGION');
UPDATE Units SET	   Combat = ROUND(1.15 * (SELECT Combat FROM Units WHERE Type = 'UNIT_SWORDSMAN'), 0)
					   WHERE Type IN ('UNIT_ROMAN_LEGION');


--
-- Promotions
--

INSERT INTO Trait_FreePromotionUnitCombats
		(TraitType, UnitCombatType, PromotionType)
SELECT	'TRAIT_PHOENICIAN_HERITAGE', Type, 'PROMOTION_CAN_MOVE_IMPASSABLE'
FROM UnitCombatInfos WHERE Type IN ('UNITCOMBAT_DIPLOMACY');

INSERT INTO Trait_FreePromotionUnitCombats
		(TraitType, UnitCombatType, PromotionType)
SELECT	'TRAIT_VIKING_FURY', Type, 'PROMOTION_AMPHIBIOUS'
FROM UnitCombatInfos WHERE Type IN (
	'UNITCOMBAT_CIVILIAN'		,
	'UNITCOMBAT_COMMAND'		,
	'UNITCOMBAT_DIPLOMACY'		,
	'UNITCOMBAT_RECON'			,
	'UNITCOMBAT_ARCHER'			,
	'UNITCOMBAT_MELEE'			,
	'UNITCOMBAT_GUN'			,
	'UNITCOMBAT_MOUNTED_ARCHER'	,
	'UNITCOMBAT_MOUNTED'		,
	'UNITCOMBAT_ARMOR'			,
	'UNITCOMBAT_SIEGE'			
);

INSERT INTO Trait_FreePromotionUnitCombats
		(TraitType, UnitCombatType, PromotionType)
SELECT	'TRAIT_IGNORE_TERRAIN_IN_FOREST', Type, 'PROMOTION_WOODSMAN'
FROM UnitCombatInfos WHERE Type IN (
	'UNITCOMBAT_CIVILIAN'		,
	'UNITCOMBAT_COMMAND'		,
	'UNITCOMBAT_DIPLOMACY'		,
	'UNITCOMBAT_RECON'			,
	'UNITCOMBAT_ARCHER'			,
	'UNITCOMBAT_MELEE'			,
	'UNITCOMBAT_GUN'			,
	'UNITCOMBAT_MOUNTED_ARCHER'	,
	'UNITCOMBAT_MOUNTED'		,
	'UNITCOMBAT_ARMOR'			,
	'UNITCOMBAT_SIEGE'			
);

INSERT INTO Trait_FreePromotionUnitCombats
		(TraitType, UnitCombatType, PromotionType)
SELECT	'TRAIT_LAND_TRADE_GOLD', Type, 'PROMOTION_DESERT_POWER'
FROM UnitCombatInfos WHERE Type IN (
	'UNITCOMBAT_CIVILIAN'		,
	'UNITCOMBAT_COMMAND'		,
	'UNITCOMBAT_DIPLOMACY'		,
	'UNITCOMBAT_RECON'			,
	'UNITCOMBAT_ARCHER'			,
	'UNITCOMBAT_MELEE'			,
	'UNITCOMBAT_GUN'			,
	'UNITCOMBAT_MOUNTED_ARCHER'	,
	'UNITCOMBAT_MOUNTED'		,
	'UNITCOMBAT_ARMOR'			,
	'UNITCOMBAT_SIEGE'			
);

/*
INSERT INTO Trait_FreePromotionUnitCombats
		(TraitType, UnitCombatType, PromotionType)
SELECT	'TRAIT_PHOENICIAN_HERITAGE', Type, 'PROMOTION_MOUNTAINEER'
FROM UnitCombatInfos WHERE Type IN (
	'UNITCOMBAT_CIVILIAN'		,
	'UNITCOMBAT_COMMAND'		,
	'UNITCOMBAT_DIPLOMACY'		,
	'UNITCOMBAT_RECON'			,
	'UNITCOMBAT_ARCHER'			,
	'UNITCOMBAT_MELEE'			,
	'UNITCOMBAT_GUN'			,
	'UNITCOMBAT_MOUNTED_ARCHER'	,
	'UNITCOMBAT_MOUNTED'		,
	'UNITCOMBAT_ARMOR'			,
	'UNITCOMBAT_SIEGE'			
);
*/

INSERT INTO Trait_FreePromotionUnitCombats
		(TraitType, UnitCombatType, PromotionType)
SELECT	'TRAIT_LAND_TRADE_GOLD', 'UNITCOMBAT_DIPLOMACY', 'PROMOTION_DESERT_POWER'
WHERE EXISTS (SELECT * FROM UnitCombatInfos WHERE Type='UNITCOMBAT_DIPLOMACY');

/*
INSERT INTO Trait_FreePromotionUnitCombats
		(TraitType, UnitCombatType, PromotionType)
SELECT	'TRAIT_VIKING_FURY', 'UNITCOMBAT_NAVAL', 'PROMOTION_NAVAL_LOGISTICS'
WHERE EXISTS (SELECT * FROM Traits WHERE Type='TRAIT_VIKING_FURY');
*/

INSERT INTO Unit_FreePromotions
		(UnitType, PromotionType)
SELECT	'UNIT_BABYLONIAN_BOWMAN', 'PROMOTION_DESERT_POWER'
WHERE EXISTS (SELECT * FROM Units WHERE Type='UNIT_BABYLONIAN_BOWMAN');

INSERT INTO Unit_FreePromotions
		(UnitType, PromotionType)
SELECT	'UNIT_AMERICAN_PIONEER', 'PROMOTION_SCOUTING_1';


		
--
-- Other
--

--UPDATE Buildings SET Defense = Defense + 100
--WHERE Type IN ('BUILDING_WALLS_OF_BABYLON');

UPDATE Buildings SET SpecialistType = 'SPECIALIST_SCIENTIST', SpecialistCount = 1
WHERE Type IN ('BUILDING_WALLS_OF_BABYLON');

DELETE FROM Trait_ImprovementYieldChanges
WHERE TraitType = 'TRAIT_SCHOLARS_JADE_HALL';

INSERT INTO Trait_ImprovementYieldChanges
		(TraitType, ImprovementType, YieldType, Yield)
SELECT 'TRAIT_SCHOLARS_JADE_HALL', 'IMPROVEMENT_FARM', 'YIELD_SCIENCE', 2
WHERE EXISTS (SELECT * FROM Traits WHERE Type='TRAIT_SCHOLARS_JADE_HALL');

INSERT INTO Trait_ImprovementYieldChanges
		(TraitType, ImprovementType, YieldType, Yield)
SELECT 'TRAIT_ALLOTMENT', 'IMPROVEMENT_FARM', 'YIELD_PRODUCTION', 1;

/*
INSERT INTO Improvement_TechFreshWaterYieldChanges
		(ImprovementType, TechType,YieldType, Yield)
SELECT	'IMPROVEMENT_TERRACE_FARM', 'TECH_CIVIL_SERVICE', 'YIELD_FOOD', '1'
WHERE EXISTS (SELECT * FROM Improvements WHERE Type='IMPROVEMENT_TERRACE_FARM' );

INSERT INTO Improvement_TechNoFreshWaterYieldChanges
		(ImprovementType, TechType,YieldType, Yield)
SELECT	'IMPROVEMENT_TERRACE_FARM', 'TECH_FERTILIZER', 'YIELD_FOOD', '1'
WHERE EXISTS (SELECT * FROM Improvements WHERE Type='IMPROVEMENT_TERRACE_FARM' );
*/

INSERT INTO Improvement_Flavors
		(ImprovementType, FlavorType, Flavor)
SELECT	'IMPROVEMENT_TERRACE_FARM', 'FLAVOR_GROWTH', '50'
WHERE EXISTS (SELECT * FROM Improvements WHERE Type='IMPROVEMENT_TERRACE_FARM' );

INSERT INTO Improvement_Flavors
		(ImprovementType, FlavorType, Flavor)
SELECT	'IMPROVEMENT_TERRACE_FARM', 'FLAVOR_PRODUCTION', '50'
WHERE EXISTS (SELECT * FROM Improvements WHERE Type='IMPROVEMENT_TERRACE_FARM' );

INSERT INTO Improvement_Flavors
		(ImprovementType, FlavorType, Flavor)
SELECT	'IMPROVEMENT_TERRACE_FARM', 'FLAVOR_GOLD', '50'
WHERE EXISTS (SELECT * FROM Improvements WHERE Type='IMPROVEMENT_TERRACE_FARM' );

/*
INSERT INTO Trait_YieldFromConstructionInCapital (TraitType, BuildingType, YieldType, YieldMod)
SELECT 'TRAIT_SCHOLARS_JADE_HALL', Type, 'YIELD_SCIENCE', 100
FROM Buildings WHERE Type IN (
	'BUILDING_LIBRARY',
	'BUILDING_UNIVERSITY',
	'BUILDING_PUBLIC_SCHOOL',
	'BUILDING_LABORATORY',
	'BUILDING_OBSERVATORY',
	'BUILDING_NATIONAL_COLLEGE',
	'BUILDING_OXFORD_UNIVERSITY',
	'BUILDING_GREAT_LIBRARY',
	'BUILDING_PORCELAIN_TOWER'
);
*/

INSERT INTO Trait_YieldFromConstruction (TraitType, BuildingType, YieldType, Yield)
SELECT 'TRAIT_POPULATION_GROWTH', Type, 'YIELD_POPULATION', 1
FROM Buildings WHERE Type IN (
	'BUILDING_HARBOR',
	'BUILDING_GARDEN',
	'BUILDING_GRANARY',
	'BUILDING_INDUS_SANITATION',
	'BUILDING_HOSPITAL',
	'BUILDING_MEDICAL_LAB'
);

/*
INSERT INTO Civilization_BuildingClassOverrides
		(CivilizationType, BuildingClassType, BuildingType)
SELECT	'CIVILIZATION_DENMARK', 'BUILDINGCLASS_HEROIC_EPIC', 'BUILDING_JELLING_STONES'
WHERE EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_DENMARK');
*/

INSERT INTO Civilization_Start_Region_Avoid
		(CivilizationType, RegionType)
SELECT	'CIVILIZATION_BABYLON', 'REGION_TUNDRA'
WHERE EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_BABYLON');

INSERT INTO Trait_FreeResourceFirstXCities (TraitType, ResourceType, ResourceQuantity, NumCities)
SELECT Type, 'RESOURCE_IRON', 2, 1
FROM Traits WHERE Type IN (
	'TRAIT_CAPITAL_BUILDINGS_CHEAPER'	,
	'TRAIT_VIKING_FURY'					,
	'TRAIT_FIGHT_WELL_DAMAGED'			
);

INSERT INTO Trait_FreeResourceFirstXCities (TraitType, ResourceType, ResourceQuantity, NumCities)
SELECT Type, 'RESOURCE_HORSE', 2, 1
FROM Traits WHERE Type IN (
	'TRAIT_TERROR'						,
	'TRAIT_AMPHIB_WARLORD'				,
	'TRAIT_WONDER_BUILDER'				,
	'TRAIT_EXTRA_BELIEF'				,
	'TRAIT_CITY_STATE_FRIENDSHIP'		
);