UPDATE Leaders SET AIBonus = 1
WHERE Type IN (
	'LEADER_ASKIA',
	'LEADER_AUGUSTUS',
	'LEADER_ELIZABETH',
	'LEADER_GENGHIS_KHAN',
	'LEADER_HARALD',
	'LEADER_ISABELLA',
	'LEADER_ODA_NOBUNAGA'
);

UPDATE Units SET RangedCombat = RangedCombat + 4
WHERE Type IN ('UNIT_CHINESE_CHUKONU');

UPDATE Units SET RangedCombat = RangedCombat - 3
WHERE Type IN ('UNIT_ENGLISH_LONGBOWMAN');

UPDATE Units SET Combat = Combat + 1
WHERE Type IN ('UNIT_DANISH_BERSERKER');

UPDATE Units SET Combat = Combat + 2
WHERE Type IN (
	'UNIT_JAPANESE_SAMURAI',
	'UNIT_AZTEC_JAGUAR',
	'UNIT_POLYNESIAN_MAORI_WARRIOR'
);

--UPDATE Buildings SET Defense = Defense + 100
--WHERE Type IN ('BUILDING_WALLS_OF_BABYLON');

UPDATE Buildings SET SpecialistType = 'SPECIALIST_SCIENTIST', SpecialistCount = 1
WHERE Type IN ('BUILDING_WALLS_OF_BABYLON');

INSERT INTO Trait_FreePromotionUnitCombats
		(TraitType, UnitCombatType, PromotionType)
SELECT	'TRAIT_LAND_TRADE_GOLD', 'UNITCOMBAT_DIPLOMACY', 'PROMOTION_DESERT_POWER'
WHERE EXISTS (SELECT * FROM UnitCombatInfos WHERE Type='UNITCOMBAT_DIPLOMACY');

/*
INSERT INTO Trait_FreePromotionUnitCombats
		(TraitType, UnitCombatType, PromotionType)
SELECT	'TRAIT_VIKING_FURY', 'UNITCOMBAT_NAVAL', 'PROMOTION_NAVAL_LOGISTICS'
WHERE EXISTS (SELECT * FROM Traits WHERE Type='TRAIT_VIKING_FURY');
*/

INSERT INTO Unit_FreePromotions
		(UnitType, PromotionType)
SELECT	'UNIT_BABYLONIAN_BOWMAN', 'PROMOTION_DESERT_POWER'
WHERE EXISTS (SELECT * FROM Units WHERE Type='UNIT_BABYLONIAN_BOWMAN');

INSERT INTO Trait_FreeUnitAtTech
		(TraitType, TechType, UnitType)
SELECT	'TRAIT_INGENIOUS', 'TECH_WRITING', 'UNIT_SCIENTIST'
WHERE EXISTS (SELECT * FROM Traits WHERE Type='TRAIT_INGENIOUS');

DELETE FROM Trait_ImprovementYieldChanges
WHERE TraitType = 'TRAIT_SCHOLARS_JADE_HALL';

INSERT INTO Trait_ImprovementYieldChanges
		(TraitType, ImprovementType, YieldType, Yield)
SELECT 'TRAIT_SCHOLARS_JADE_HALL', 'IMPROVEMENT_FARM', 'YIELD_SCIENCE', 2
WHERE EXISTS (SELECT * FROM Traits WHERE Type='TRAIT_SCHOLARS_JADE_HALL');

INSERT INTO Improvement_TechFreshWaterYieldChanges
		(ImprovementType, TechType,YieldType, Yield)
SELECT	'IMPROVEMENT_TERRACE_FARM', 'TECH_CIVIL_SERVICE', 'YIELD_FOOD', '1'
WHERE EXISTS (SELECT * FROM Improvements WHERE Type='IMPROVEMENT_TERRACE_FARM' );

INSERT INTO Improvement_TechNoFreshWaterYieldChanges
		(ImprovementType, TechType,YieldType, Yield)
SELECT	'IMPROVEMENT_TERRACE_FARM', 'TECH_FERTILIZER', 'YIELD_FOOD', '1'
WHERE EXISTS (SELECT * FROM Improvements WHERE Type='IMPROVEMENT_TERRACE_FARM' );

INSERT INTO Improvement_Flavors
		(ImprovementType, FlavorType, Flavor)
SELECT	'IMPROVEMENT_TERRACE_FARM', 'FLAVOR_GROWTH', '50'
WHERE EXISTS (SELECT * FROM Improvements WHERE Type='IMPROVEMENT_TERRACE_FARM' );

INSERT INTO Improvement_Flavors
		(ImprovementType, FlavorType, Flavor)
SELECT	'IMPROVEMENT_TERRACE_FARM', 'FLAVOR_PRODUCTION', '50'
WHERE EXISTS (SELECT * FROM Improvements WHERE Type='IMPROVEMENT_TERRACE_FARM' );

INSERT INTO Improvement_Flavors
		(ImprovementType, FlavorType, Flavor)
SELECT	'IMPROVEMENT_TERRACE_FARM', 'FLAVOR_GOLD', '50'
WHERE EXISTS (SELECT * FROM Improvements WHERE Type='IMPROVEMENT_TERRACE_FARM' );

/*
INSERT INTO Trait_YieldFromConstructionInCapital (TraitType, BuildingType, YieldType, YieldMod)
SELECT 'TRAIT_SCHOLARS_JADE_HALL', Type, 'YIELD_SCIENCE', 100
FROM Buildings WHERE Type IN (
	'BUILDING_LIBRARY',
	'BUILDING_UNIVERSITY',
	'BUILDING_PUBLIC_SCHOOL',
	'BUILDING_LABORATORY',
	'BUILDING_OBSERVATORY',
	'BUILDING_NATIONAL_COLLEGE',
	'BUILDING_OXFORD_UNIVERSITY',
	'BUILDING_GREAT_LIBRARY',
	'BUILDING_PORCELAIN_TOWER'
);
*/

INSERT INTO Trait_YieldFromConstruction (TraitType, BuildingType, YieldType, Yield)
SELECT 'TRAIT_POPULATION_GROWTH', Type, 'YIELD_POPULATION', 1
FROM Buildings WHERE Type IN (
	'BUILDING_LIGHTHOUSE',
	'BUILDING_GARDEN',
	'BUILDING_GRANARY',
	'BUILDING_SANITATION_SYSTEM',
	'BUILDING_HOSPITAL',
	'BUILDING_MEDICAL_LAB'
);

/*
INSERT INTO Civilization_BuildingClassOverrides
		(CivilizationType, BuildingClassType, BuildingType)
SELECT	'CIVILIZATION_DENMARK', 'BUILDINGCLASS_HEROIC_EPIC', 'BUILDING_JELLING_STONES'
WHERE EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_DENMARK');
*/

INSERT INTO Civilization_Start_Region_Avoid
		(CivilizationType, RegionType)
SELECT	'CIVILIZATION_BABYLON', 'REGION_TUNDRA'
WHERE EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_BABYLON');