-- EN_US/Leaders.sql
/* Traits */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_ART_OF_WAR', 'Great Generals see +2 tiles farther and provide extra strength.[NEWLINE]Starts with a Warrior and Great General.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_FASTER_RANGED_SHORT', 'Usurper', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_FASTER_RANGED', '[ICON_RANGE_STRENGTH] Ranged units move faster.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_FIGHT_WELL_DAMAGED', 'Wounded units deal full damage.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_CAPITAL_BUILDINGS_CHEAPER', '25% [ICON_PRODUCTION] Production towards any buildings that already exist in the [ICON_CAPITAL] Capital.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_CITY_STATE_BONUSES', '25% higher rewards from friendly and allied City-States.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_CITY_STATE_FRIENDSHIP', 'City-State [ICON_INFLUENCE] Influence degrades at half and recovers at twice the normal rate. Militaristic City-State friends give units with +20% [ICON_STRENGTH] Strength.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS_SHORT', 'Scourge of God', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS', 'Barbarian camps surrender when defeated.[NEWLINE]Starts with a Horse Archer.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_CONVERTS_SEA_BARBARIANS', 'Melee ships capture defeated enemy ships.[NEWLINE]Starts with a Warrior and Liburna.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_CULTURE_FROM_KILLS', 'Gains [ICON_CULTURE] Culture from killing enemy units.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_ENGINEERING_SHORT', 'Prussian Values', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_ENGINEERING', '+2 [ICON_PRODUCTION] Production for Scientists, and +2 [ICON_RESEARCH] Science for Engineers.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_ENHANCED_CULTURE', '+3 [ICON_CULTURE] Culture per turn from Cities before discovering Steam Power.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_ENHANCED_GOLDEN_AGES', '+50% [ICON_CULTURE] Culture and +1[ICON_MOVES] Movement during [ICON_GOLDEN_AGE] Golden Ages.[NEWLINE]Starts with an Immortal instead of a Warrior.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_FIGHT_WELL_DAMAGED', 'Damaged units fight at full strength.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_GREAT_ANDEAN_ROAD', 'Units move faster on Hills. Free maintenance for roads and railroads on Hills; half cost elsewhere.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_HARAPPAN_ENGINEERING_SHORT', 'Harappan Engineering', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_HARAPPAN_ENGINEERING', '+1 [ICON_MOVES] Movement for civilian units.[NEWLINE]Starts with a Worker instead of a Warrior.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_IGNORE_TERRAIN_IN_FOREST', 'Faster movement in Forests and Jungle, which count as roads in friendly territory.[NEWLINE]Starts with a Mohawk Warrior instead of a Warrior.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_INGENIOUS', '+25% Great Scientist spawn rate and receives one at Writing.[NEWLINE]Starts with a Bowman instead of a Warrior.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_LAND_TRADE_GOLD_SHORT', 'Desert Caravans', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_LAND_TRADE_GOLD', 'Each luxury resource increases [ICON_GOLD] Gold income by 5%, and units move faster in Desert terrain.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_LONG_COUNT', 'After researching Theology, receive a bonus Great Person at the end of every Maya Long Count calendar cycle (every 394 years).[NEWLINE]Starts with an Atlatlist instead of a Warrior.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_WONDER_BUILDER', '+20% [ICON_PRODUCTION] Production towards Wonder construction.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_OCEAN_MOVEMENT', '+30 [ICON_WAR] Experience for naval units.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_EXTRA_BELIEF', 'Choose one more Belief than normal when you found a Religion.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_POPULATION_GROWTH', 'Food buildings add 1 [ICON_CITIZEN] Population when constructed.[NEWLINE]Starts with a Worker instead of a Warrior.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_RAZE_AND_HORSES', 'Barbarian camps surrender when defeated for double [ICON_GOLD] Gold.[NEWLINE]Starts with a Horse Archer.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_RIVER_EXPANSION', '+1 sight for land units, and -50% [ICON_GOLD] Cost to purchase tiles.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_SCHOLARS_JADE_HALL_SHORT', 'Joseon Dynasty', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_SCHOLARS_JADE_HALL', '+2 [ICON_RESEARCH] Science from Farms.[NEWLINE]Starts with a Worker instead of a Warrior.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_SEVEN_CITIES', 'Double yields from Natural Wonders, plus 100 [ICON_GOLD] when discovered.[NEWLINE]Starts with a Scout instead of a Warrior, and receives a Caravel at Compass.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_STRATEGIC_RICHES', '+1 [ICON_PRODUCTION] Production and double quantity from Strategic Resources.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_TERROR', '+1 [ICON_MOVES] Movement for mounted and vanguard units. +25% extra yields from capturing City-States. Starts with a Scout instead of a Warrior.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_VIKING_FURY_SHORT', 'Longships', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_VIKING_FURY', 'Faster and stronger embarkation across water, and melee units pillage faster.', '', '');
/* Units */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UNIT_HELP_MUSLIM_CAVALRY', 'Unique Songhai mounted unit. Mandekalu Cavalry starts with the Siege promotion, unlike the Knight it replaces.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UNIT_HELP_SAMURAI', 'Powerful Medieval soldier unique to the the Japanese. Samurai can attack twice per turn, and are stronger than the Longswordsmen they replace.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_CIV5_BABYLON_BOWMAN_HELP', 'Unique Babylonian archer unit. The Bowman is stronger than the Archer it replaces, and move faster in deserts.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_CIV5_DENMARK_BERSERKER_HELP', 'Soldier of the Medieval era unique to Denmark. The Berserker starts with the Charge promotion, unlike the Longswordsman it replaces.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UNIT_HELP_PANZER', 'Mobile unit unique to Germany. The Panzer has higher strength, speed, and visibility than the Tank it replaces.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UNIT_HELP_JAGUAR', 'Early-game soldier unique to the Aztecs. The Jaguar heals damage when it kills an enemy, and fights more effectively in Jungle than the Warrior it replaces.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UNIT_HELP_MINUTEMAN', 'Renaissance Vanguard Unit unique to the Americans. It is stronger than the Skirmisher it replaces, sees farther, and moves faster in rough terrain.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UNIT_HELP_MUSKETEER', 'One of the first gunpowder units of the game, unique to the French. Musketeers have a combat bonus outside of friendly territory, unlike the Musketman it replaces.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UNIT_IROQUOIAN_MOHAWKWARRIOR_STRATEGY', 'Soldier unique to the Iroquois. The Mohawk Warrior fights stronger in Forest and Jungle than the Swordsman it replaces.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UNIT_OTTOMAN_JANISSARY_STRATEGY', 'Soldier unique to the Ottomans. The Janissary is much stronger on the attack and heals after kills, unlike the Musketman it replaces.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_MEDIC_GENERAL_HELP', 'Units within 1 tile [COLOR_POSITIVE_TEXT]Heal 4 Additional HP[ENDCOLOR] per turn.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_CIV5_MONGOLIA_KESHIK_HELP', 'The unique Mongolian replacement for the Knight moves faster, is ranged, and does not share the Knight''s vulnerabilities to Cities or Pikemen. The Keshik also earns experience more quickly.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UNIT_HELP_FOREIGN_LEGION', 'Basic Industrial Era soldier unique to the French. The Foreign Legion costs much less than the Infantry it replaces.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UNIT_HELP_ROMAN_LEGION', 'Powerful Roman soldier of the Classical Era with a bonus against Cities. The Legion has higher strength than the Swordsman it replaces, extra defense against ranged attacks, and can build roads at twice the speed of Workers.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UNIT_HELP_INDIAN_WAR_ELEPHANT', 'Powerful mobile unit unique to India. Unlike the Horseman it replaces, the War Elephant is ranged, does not require horses, and has no vulnerability to Spearmen.', '', '');
/* Misc */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILD_MOAI_HELP', '+3 [ICON_CULTURE] Culture.[NEWLINE]+1 [ICON_CULTURE] Culture per adjacent Moai.[NEWLINE][ICON_LOCKED] Must be next to Coast.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_CIV5_IMPROVEMENTS_MOAI_HELP', '+3 [ICON_CULTURE] Culture.[NEWLINE]+1 [ICON_CULTURE] Culture per adjacent Moai.[NEWLINE][ICON_LOCKED] Must be next to Coast.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_POLYNESIAN_SCENARIO_BUILD_MOAI_HELP', '+3 [ICON_CULTURE] Culture.[NEWLINE]+1 [ICON_CULTURE] Culture per adjacent Moai.[NEWLINE][ICON_LOCKED] Must be next to Coast.', '', '');
/*  Jelling Stones */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_JELLING_STONES', 'Jelling Stones', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_JELLING_STONES_STRATEGY', 'The Jelling Stones are a National Wonder unique to Denmark. This wonder gives all units built in this city the ''Morale'' promotion, increasing their combat strength by +20. Jelling Stones also give the city a large amount of culture for each city captured, unlike the Heroic Epic it replaces.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_JELLING_STONES_PEDIA', 'The Jelling stones are massive carved runestones from the 10th century, found at the town of Jelling in Denmark. The older of the two Jelling stones was raised by King Gorm in memory of his wife Thyra. The larger of the two stones was raised by Harald Bluetooth, King Gorm''s son. Harald constructed the second stone in memory of his parents, celebration of his conquest of Denmark and Norway, and his conversion of the Danes to Christianity. The runic inscriptions on these stones are considered the most well known in Denmark.', '', '');
/*  Jade Hall */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_JADE_HALL', 'Jade Hall', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_JADE_HALL_STRATEGY', 'The Jade Hall is a National Wonder unique to Korea. This wonder gives a free technology, increases the city''s science output, and increases the [ICON_RESEARCH] Science of all specialists in all cities.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_JADE_HALL_PEDIA', 'King Sejong oversaw the development of the Chiphyonjon, the Jade Hall of Scholars, the professional scholars who helped research social and political questions for the King and government. The Jade Hall would be considered a "think tank" by governments today.', '', '');
/*  Indus Sanitation */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-21'), 'TXT_KEY_BUILDING_INDUS_SANITATION', 'Indus Sanitation', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-21'), 'TXT_KEY_BUILDING_INDUS_SANITATION_STRATEGY', 'Clean drinking water from a Sanitation System improves [ICON_FOOD] Food from Rivers. It also decreases the amount of food a city needs to increase in size by 40%. Build Sanitation Systems in cities that you want to grow large over time.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-21'), 'TXT_KEY_BUILDING_INDUS_SANITATION_PEDIA', 'The Harappan civilization of the Indus River Valley designed the world''s first known urban sanitation systems around 2600 BCE. Individual homes or groups of homes obtained water from wells. Waste water was directed from rooms set aside for bathing to covered drains lining the major streets. The massive walls of Harappan cities were speculated to protect from flooding. These Harappan hydraulic engineering systems were even more efficient than those of many areas of Pakistan and India today, achieving large urban cities with relatively little agriculture development.', '', '');
/*  Pioneer Fort */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_AMERICAN_FORT', 'Pioneer Fort', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_AMERICAN_FORT_STRATEGY', 'The Pioneer Fort is an American unique building increasing a city''s Defense Strength, making the city more difficult to capture. It also increases the city''s growth rate. The Pioneer Fort is quite useful for cities located along a civilization''s frontier.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_AMERICAN_FORT_CIV', 'American pioneers are any of the people in U.S. history who migrated west from the Atlantic coast to settle and develop new areas. The term especially refers to those who were going to settle territory new to European or American society, although the territory may have been inhabited by or utilized by native peoples.[NEWLINE][NEWLINE]The pioneer concept and ethos greatly predate the migration to parts of the United States now called ''western'' states, as many places now considered as East were also settled by pioneers from the coast. For example, Daniel Boone, a key figure in American pioneer history, settled in Kentucky, when that ''Dark and Bloody Ground'' was still undeveloped.[NEWLINE][NEWLINE]One important development in the Western settlement was the Homestead Act, which provided formal legislation which regulated the settlement process.', '', '');
/*  Pioneer */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UNIT_AMERICAN_PIONEER', 'Pioneer', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UNIT_AMERICAN_PIONEER_HELP', 'Founds new Cities to expand your empire.[NEWLINE][NEWLINE][ICON_FOOD] Growth of the City is stopped while this Unit is being built.[NEWLINE]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UNIT_AMERICAN_PIONEER_STRATEGY', 'The Pioneer is an American Unique Unit. It moves faster than the settler it replaces.[NEWLINE][NEWLINE]Use this unit to construct new cities. It cannot defend itself, so accompany it with a combat unit.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UNIT_AMERICAN_PIONEER_CIV', 'American pioneers are any of the people in U.S. history who migrated west from the Atlantic coast to settle and develop new areas. The term especially refers to those who were going to settle territory new to European or American society, although the territory may have been inhabited by or utilized by native peoples.[NEWLINE][NEWLINE]The pioneer concept and ethos greatly predate the migration to parts of the United States now called ''western'' states, as many places now considered as East were also settled by pioneers from the coast. For example, Daniel Boone, a key figure in American pioneer history, settled in Kentucky, when that ''Dark and Bloody Ground'' was still undeveloped.[NEWLINE][NEWLINE]One important development in the Western settlement was the Homestead Act, which provided formal legislation which regulated the settlement process.', '', '');
/* Steam Mill */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_ENGLISH_STEAM_MILL', 'Steam Mill', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_ENGLISH_STEAM_MILL_STRATEGY', 'The Steam Mill is an English Unique Building. It improves the yield of luxury resources and can be built in any city, unlike the Workshop it replaces.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_ENGLISH_STEAM_MILL_CIV', 'A transition began towards machine-based factories in Great Britain''s economy in the 1700s, previously reliant on manual labor and draft animals. These precursors to the Industrial Revolution started with the mechanization of the textile industries. Trade expansion was enabled by the introduction of canals, improved roads, and railways. Wider utilization of water wheels and the introduction of steam power pushed dramatic increases in production capacity. The development of all-metal machine tools in the early 1800s facilitated the construction of increasingly refined  production machines for manufacturing in a wide variety of industries.', '', '');
/* Dojo */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_JAPANESE_DOJO', 'Dojo', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_JAPANESE_DOJO_STRATEGY', 'The Dojo is a Japanese Unique Building replacing the Barracks. It improves [ICON_WAR] Experience for units trained here, and increases [ICON_CULTURE] Culture from nearby strategic resources.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_JAPANESE_DOJO_PEDIA', 'A Japanese dojo (''place of the way'') is a gathering place to conduct training, examinations, and other related encounters for the ''do'' arts. Dojos were initially adjunct to temples. In Japan any physical training facility, including professional wrestling schools, may be called dojo because of its close martial arts roots.', '', '');
/* Shrine */
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_JAPANESE_SHRINE', 'Shinto Shrine', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_JAPANESE_SHRINE_STRATEGY', 'The Shinto Shrine is a Japanese Unique Building. It increases a city''s happiness and provides culture from all luxury resources, unlike the Monastery it replaces. The Shinto Shrine cannot be built unless the city has such an improved resource nearby.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILDING_JAPANESE_SHRINE_CIV', 'In Japan, Shinto shrines exist side by side with Buddhist temples, and are the most numerous, famous, and important religious sites in Japan. A Shinto shrine is a structure or object whose main purpose is to house one or more Shinto kami (spirits, natural forces, or essence). Kami can reside in almost anything natural or man-made, from Mt. Fuji to a small jewel.  As such, these shrines are common and vary widely in scope. The Shrine itself can be a large building or small object, along a roadside, or might even be carried by people.[NEWLINE][NEWLINE]Like Buddhist temples, Shinto shrines are not primarily a place of worship. The shrine''s most important buildings are used for the safekeeping of sacred objects. There are specialized buildings for certain rites, but these are usually open only to a limited number of participants. Religious mass gatherings in the style of Christian churches do not take place with regularity and are not held inside the shrine. If many people are involved in a ceremony, it will assume a festive character and will be held outdoors.', '', '');



UPDATE LoadedFile SET Value=1 WHERE Type='GEM_Leaders.sql';
