-- EN_US/Terrain.sql
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_RESOURCE_MOVIES', 'Movies', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_CIV5_RESOURCE_MOVIES_TEXT', 'A movie, also called a film or motion picture, is a series of still images on a strip of plastic which, when run through a projector and shown on a screen, creates the illusion of moving images. A film is created by photographing actual scenes with a motion picture camera; by photographing drawings or miniature models using traditional animation techniques; by means of CGI and computer animation; or by a combination of some or all of these techniques and other visual effects. The process of filmmaking is both an art and an industry.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILD_FORT_REC', 'It will improve the [ICON_STRENGTH] Defense of any military unit stationed in this tile, and deals 20 damage to adjacent enemies.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILD_FORT_HELP', '[COLOR_NEGATIVE_TEXT]Costs[ENDCOLOR] 3 [ICON_GOLD] Gold per turn to maintain.[NEWLINE][NEWLINE]+50% [ICON_STRENGTH] Defensive Strength for any Unit stationed in this Tile, and deals 20 damage to adjacent enemies.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_CIV5_IMPROVEMENTS_FORT_TEXT', '[COLOR_NEGATIVE_TEXT]Costs[ENDCOLOR] 3 [ICON_GOLD] Gold per turn to maintain.[NEWLINE][NEWLINE]A fort is a special improvement that improves a hex''s defensive bonus, and deals 20 damage to adjacent enemies. However, these effects do not apply in enemy territory.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_CIV5_FEATURES_EL_DORADO_HELP', 'Grants 100 [ICON_GOLD] Gold to the first player to discover it.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_FEATURE_ATOLL', 'Isles', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_CIV5_FEATURES_ATOLL', 'Isles', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_CIV5_FEATURES_ATOLL_TEXT', 'An island is any piece of sub-continental land that is surrounded by water. Very small islands can be called isles, cays or keys.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_SPECIALISTSANDGP_CITADEL_HEADING4_BODY', '{TXT_KEY_BUILD_CITADEL_HELP}', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_BUILD_CITADEL_HELP', '[ICON_STRENGTH] +100% [COLOR_POSITIVE_TEXT]Defense[ENCOLOR] on this tile.[NEWLINE][ICON_RANGED_STRENGTH] Deals 30 [COLOR_POSITIVE_TEXT]Damage[ENCOLOR] per turn to nearby enemies.[NEWLINE][ICON_CULTURE] Expands borders to nearby tiles.[NEWLINE][ICON_LOCKED] Requires friendly territory.', '', '');



UPDATE LoadedFile SET Value=1 WHERE Type='GEM_Terrain.sql';
